### ISSUE TITLE
How to adjust the number displayed in digital format in excel

### ISSUE THREAD

**Issue by dafa168** [rap2hpoutre/fast-excel#101]
In order to facilitate statistics, the operating colleagues want to display the numbers in digital format in excel.

In order to facilitate statistics, the operating colleagues want to display the numbers in digital format in excel.
When the number is uniformly formatted into a numeric int type and output to excel, but it is still displayed as a string in excel, please help me with it. Thank you

**Comment by dafa168** [comment]
如何调整数字在excel中显示为数字格式

为了方便做统计，运营同事想把数字在excel中显示为数字格式
当把数字统一格式化为数字int类型输出到excel中，但是在excel中还是显示为字符串， 请你帮帮忙处理下。谢谢

**Comment by rap2hpoutre** [comment]
Hi @dafa168, thank you for contributing! Since this lib is based on Spout, it seems it's not possible to specify the column format :/. If you need this kind of feature, maybe you should use Laravel-Excel (https://github.com/Maatwebsite/Laravel-Excel)

**Comment by NazarAli** [comment]
i have same  problem

**Comment by klukiyan** [comment]
@dafa168 @NazarAli 
I had the same issue when trying to export to excel the result of SQL query.
resolved by formatting data as number in the collection before sending it to fast excel
```php
      foreach($data as $rowkey=>$datarow){
        foreach($datarow as $colkey=>$col){
          if(is_numeric($col)) $datarow->{$colkey} = $col * 1;
        }
        $data[$rowkey] = $datarow;
      }
      $data2 = collect($data);
 ```
