### ISSUE TITLE
How to handle situation where I have 2 heading rows? Could we read raw rows?

### ISSUE THREAD

**Issue by realtebo** [rap2hpoutre/fast-excel#102]
I'd like to be able to received 'raw' row data because my excel sheet headers are a bit complicated.

We have 2 rows, in first row some cells are grouped, so 'real' header is the 2nd one. But We can't rely on header cell names because some are duplicated (because of first row that give the context to the user).

So, in brief, could we simply read row by row?

**Comment by rap2hpoutre** [comment]
If you want to read row by row, I suggest you use `Spout` directly (http://opensource.box.com/spout/).

You could do something like this:

```php
use Box\Spout\Reader\Common\Creator\ReaderEntityFactory;

$reader = ReaderEntityFactory::createReaderFromFile('/path/to/file.ext');

$reader->open($filePath);

foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $row) {
        // do stuff with the row
        $cells = $row->getCells();
    }
}

$reader->close();
```

This package goal is to quickly import CSV, XLSX, etc. to get it as Collections in Laravel by getting first column as header. It seems it does not fit your needs.

Still maybe we could implement something for ignoring some rows. Let me know what you think. (I want to keep this package simple and light, but I understand your need).

**Comment by rap2hpoutre** [comment]
It's also possible with this package too: https://github.com/rap2hpoutre/fast-excel/issues/86.

Use this code:

```php
$users = (new FastExcel)->withoutHeaders()->import('file.xlsx', function ($line) {
    // Skip if empty or first line (i.e. header), ... 
    // ... return the object otherwise (without the first columns)
});

```

**Comment by rap2hpoutre** [comment]
Update to 1.2.2 to make it work.
