### ISSUE TITLE
Could not open for reading , Stream wrapper used is not supported for this type of file.

### ISSUE THREAD

**Issue by iamkatta** [rap2hpoutre/fast-excel#104]
Hello,

I have a valid format file, but i am getting **Could not open for reading , Stream wrapper used is not supported for this type of file.** error, help me in solving the issue.

This is my code.

$users = (new FastExcel)->import('path/to/my/file.xlsx', function ($line) {
            return User::create([
                'name' => $line['Name'],
                'email' => $line['Email'],
                'password'=>$line['Password'],
            ]);
        });

This is the file I used  https://docs.google.com/spreadsheets/d/1JKOowTGPyyanMf4f-3pDOxnjbXERMJnssvGlUoNXHNo/edit?usp=sharing

Thanks

**Comment by rap2hpoutre** [comment]
I just tested your file (https://github.com/rap2hpoutre/fast-excel/blob/master/tests/test104.xlsx) in a unit test and it works. Could you please check that your file is actually an XLSX?

Here is the unit test I just wrote to test your issue : https://github.com/rap2hpoutre/fast-excel/blob/535e88fdd635500291673e81f789d59fbb6932e4/tests/IssuesTest.php#L159-L170

**Comment by rap2hpoutre** [comment]
Closed due to lack of activity. Feel free to re-open :).

**Comment by Walt2018** [comment]
same issue

Could not open for reading! Stream wrapper used is not supported for this type of file.
