### ISSUE TITLE
excel corruption on server

### ISSUE THREAD

**Issue by mrezagolestan** [rap2hpoutre/fast-excel#105]
all the things right in local, but exported excel corrupted when i export in the server

**Comment by rap2hpoutre** [comment]
Hi, thank you for your contribution. Could you please elaborate? (code sample, exported file, etc.)

**Comment by rap2hpoutre** [comment]
Closed due to lack of activity. Feel free to re-open :).

**Comment by SevymolSebastian** [comment]
When I trying to export 1 lakh data, the exported file is corrupted. The file size is 0KB.

![Screenshot (27)](https://github.com/rap2hpoutre/fast-excel/assets/51734783/a6764e2b-fde2-4ce1-9592-215cc081be0a)

 ```
$sheets = new SheetCollection([
     'Data'=>$data,
]);
$style = (new StyleBuilder())->setFontBold()->setFontSize(11)->build();
$rows_style = (new StyleBuilder())->setFontSize(11)->setShouldWrapText()->build();
 return (new FastExcel($sheets))->headerStyle($style)->rowsStyle($rows_style)->export($path);
```

I tried 80000 data to export, it works properly.
