### ISSUE TITLE
enclose all fields 

### ISSUE THREAD

**Issue by sheidin** [rap2hpoutre/fast-excel#106]
Hello, 

Is it possible to apply enclosure to all fields? 
Currently, I see that enclosure applied only to a few of my columns and I need to apply it to all of them.

Thanks,
Ilya

**Comment by rap2hpoutre** [comment]
Hi, thank you for your contribution. This lib uses Spout under the hood, and it seems it does not accept this option: http://opensource.box.com/spout/docs/#configuration-for-csv. Feel free to open an issue directly on [spout repository](https://github.com/box/spout) and be sure I will update if they add this feature!
