### ISSUE TITLE
Error when importing excel file

### ISSUE THREAD

**Issue by nikshakirin** [rap2hpoutre/fast-excel#108]
i got this error when importing excel file to mysql database.
weird thing is, the data is imported succesfully in my mysql database but it still throw that error page.

SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'plandate' at row 1 (SQL: insert into `plannings` (`staffno`, `plant_id`, `plandate`, `workcentre`, `partno`, `partdesc`, `model`, `itemgroup`, `oph`, `status`, `planout`, `updated_at`, `created_at`) values (M0542, 1, , ?, ?, ?, ?, ?, ?, Not Started, ?, 2019-08-02 10:17:03, 2019-08-02 10:17:03))

here is my function on controller.
$plannings = (new FastExcel)->import($request->file, function ($line) {
                return Planning::Create([
                    'staffno'     => Auth::user()->staffno,
                    'plant_id'     => Auth::user()->plant_id,
                    'plandate'    => $line['PLAN DATE'],
                    'workcentre'    => $line['WORK CENTRE'],
                    'partno'    => $line['PART NUMBER'],
                    'partdesc'    => $line['PART DESCRIPTION'],
                    'model'    => $line['MODEL'],
                    'itemgroup'    => $line['ITEM GROUP'],
                    'oph'    => $line['CT/SPH'],
                    'status'    => 'Not Started',
                    'planout'    => $line['PLAN OUTPUT'],
                ]);
            });

Thanks

**Comment by rap2hpoutre** [comment]
Hi and thank you for your contribution.

`$line['PLAN DATE']` seems to be an empty string in your case. An empty string is not a valid date. 

If the columns `plandate` is nullable, you could try to send a null value:

    'plandate' => $line['PLAN DATE'] ?: null,

If the columns `plandate` is not nullable and you [specified it's a date in your model](https://laravel.com/docs/5.8/eloquent-mutators#date-mutators), you could try to send a default value with now:

    'plandate' => $line['PLAN DATE'] ?: now(),


If the columns `plandate` is not nullable and it's not a date columns, you could try to send a default value with a date string:

    'plandate' => $line['PLAN DATE'] ?: '2019-08-02 10:17:03',

Let me know if it fixed your problem.

**Comment by nikshakirin** [comment]
Thanks for the response.
i still have the same error when importing.

$line['PLAN DATE'] is not an empty cell in excel file,

the data is uploaded in mysql table but laravel throw error as shown in question after all data uploaded instead of redirect to next page.

Thanks

**Comment by elminson** [comment]
This will look silly but can you try replace ALL  your variables with space
with a underscore?

$line['PLAN DATE'] with $line['PLAN_DATE']

**Comment by elminson** [comment]
By the way $line['CT/SPH'] is invalid name for a array key so you will get
error in all the places where you use invalid array key
Also using array key names with spaces is invalid.

**Comment by mengdodo** [comment]
check you excel ,maybe some bad data

**Comment by rap2hpoutre** [comment]
I close it since there is no recent answer from @nikshakirin. Feel free to reopen if you consider I should have not closed it.
