### ISSUE TITLE
SheetCollection issue

### ISSUE THREAD

**Issue by dbenn-marco** [rap2hpoutre/fast-excel#111]
Is it possible to build SheetCollection with a function return like you can with the base export option?
Or is there better example of using the SheetCollection?

**Comment by rap2hpoutre** [comment]
Hi, thank you for contributing! I don't really understand your question. What do you want to do? Could you please give an example?

**Comment by dbenn-marco** [comment]
My apologies for being a little vague.

So currently I use FastExcel like this.
(new FastExcel($data))->export(storage_path('app/reports/some_file.xlsx'), function ($data) {
	return [
		'A' => $data->content_a,
		'B' => $data->content_b,
		'C' => $data->content_c,
	];
});
Which works perfectly on single sheet excel files.

I was wondering if it was possible to use the SheetCollection in a similar manner, such as:

$sheets = new SheetCollection([
    'Users' => function ($dataA) {
	return [
		'A1' => $dataA->content_a,
		'A2' => $dataA->content_b,
		'A3' => $dataA->content_c,
	];
    },
    'Second sheet' => function ($dataB) {
	return [
		'B1' => $dataB->content_a,
		'B2' => $dataB->content_b,
		'B3' => $dataB->content_c,
	];
    },
]);

**Comment by TiagoKnow** [comment]
I ask the same question

**Comment by rap2hpoutre** [comment]
It is now possible, source: https://github.com/rap2hpoutre/fast-excel#export-multiple-sheets
