### ISSUE TITLE
Laravel 6.0 support

### ISSUE THREAD

**Issue by vedmant** [rap2hpoutre/fast-excel#117]
Please add Laravel 6.0 support

**Comment by rap2hpoutre** [comment]
@vedmant see #118

**Comment by vedmant** [comment]
You'll need to set ^6.0, not 6.0.*, Laravel will have semantic versioning.

**Comment by rap2hpoutre** [comment]
@vedmant 

> Laravel will have semantic versioning.

I did not know, thanks. Is there a post or a link about this?

**Comment by vedmant** [comment]
https://laravel.com/docs/6.0/releases#versioning-scheme

**Comment by rap2hpoutre** [comment]
@vedmant Thanks! fixed!

**Comment by rap2hpoutre** [comment]
Available in 1.3.1
