### ISSUE TITLE
Class 'Rap2hpoutre\FastExcel\FastExcel' not found

### ISSUE THREAD

**Issue by devendrakavya** [rap2hpoutre/fast-excel#120]
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Rap2hpoutre\FastExcel\FastExcel;
use App\User;

class TestController extends Controller
{
    public function test()
    {
        // Load users
        $users = User::all();

        // Export all users
        (new FastExcel($users))->export('file.xlsx');
    }
}

**Comment by rap2hpoutre** [comment]
duplicate of #121
