### ISSUE TITLE
Class 'Rap2hpoutre\FastExcel\FastExcel' not found

### ISSUE THREAD

**Issue by devendrakavya** [rap2hpoutre/fast-excel#121]
I have already add aliases in config/app.php
like this 'FastExcel' => Rap2hpoutre\FastExcel\Facades\FastExcel::class,

use Illuminate\Http\Request;
use Rap2hpoutre\FastExcel\FastExcel;
use App\User;

class TestController extends Controller
{
    public function test()
    {
        // Load users
        $users = User::all();

        // Export all users
        (new FastExcel($users))->export('file.xlsx');
    }

**Comment by rap2hpoutre** [comment]
Hi, thank you for contributing.

Did you run `composer require rap2hpoutre/fastexcel`?

**Comment by CodeNinjaUG** [comment]
hi composer require rap2hpoutre/fastexcel? this is run on installing the package the error comes after installation
