### ISSUE TITLE
Counting processed and total rows of xlsx file

### ISSUE THREAD

**Issue by kaizokupuffball** [rap2hpoutre/fast-excel#123]
Is there any way to implement any way of getting the total amount of rows in the xlsx file when importing? This is for a progress-bar purpose, so getting the total amount of rows before I start adding the values to the database would be nice. Also, is there a way of getting the row number of current processing row? Or do I need to count this manually with something like `++$row;`

**Comment by rap2hpoutre** [comment]
Hi @kaizokupuffball, thank you for your contribution and sorry for late answer. See: https://github.com/rap2hpoutre/fast-excel/issues/133.

> Also, is there a way of getting the row number of current processing row? Or do I need to count this manually with something like ++$row;

I guess you have to count it manually...
