### ISSUE TITLE
FileNotFound Exception when provided empty array

### ISSUE THREAD

**Issue by vishal-chauhan97** [rap2hpoutre/fast-excel#125]
After providing empty excel sheet as input, the call to donwload function returns exception.
Tried with the clone of this repository and removed the data from the excel included in the test, it gave the same error.
Steps to reproduce : 
 call this function testExportWithHeaderStyle() inside the FastExcelTest.PHP
with empty excel sheet.

Also this same issue appears when download or export fuction is provided with empty array.

**Comment by rap2hpoutre** [comment]
Hi @vishal-chauhan97 thank you for contributing! 
✨It has been fixed in v1.3.2 thanks to @johanrosenson 🎊
