### ISSUE TITLE
Download Excel File "This site can't be reached"

### ISSUE THREAD

**Issue by Pelegrinetti** [rap2hpoutre/fast-excel#126]
Hi, I have the same problem in the closed issue below. I tried the @elminson steps but the error still happens.

https://github.com/rap2hpoutre/fast-excel/issues/42

OS: Ubuntu
PHP: 7.1
Browser: Google Chrome

The error happen when:
```return (new FastExcel($data))->download("file.xlsx");```

P.S.: When *$data* is an array the excel file is generated but is empty, when I convert array to collection this error happen. Browser message: ERR_INVALID_RESPONSE.

**Comment by suicodave** [comment]
Your array may be too large that it blows up php and unable to respond.

**Comment by Pelegrinetti** [comment]
@suicodave Is there any solution for this case?

**Comment by suicodave** [comment]
@Pelegrinetti https://github.com/rap2hpoutre/fast-excel#export-large-collections-with-chunk

**Comment by Pelegrinetti** [comment]
Thank you so much for your help @suicodave
