### ISSUE TITLE
How can you read Images from Excel?

### ISSUE THREAD

**Issue by popstheman** [rap2hpoutre/fast-excel#127]
@rap2hpoutre I have an excel file from which I can read the data with no issues using your library. Now I need to read the images in the excel file? Is there a way to do it? 

Thanks

**Comment by rap2hpoutre** [comment]
Hi @popstheman, thank you for contributing (and sorry for late answer). As far as I know, there is no way to read images with Spout (which is the library that is used by Fast Excel). Source: https://github.com/box/spout/issues/137. You can try with https://github.com/Maatwebsite/Laravel-Excel, but I'm not sure it supports images importation.
