### ISSUE TITLE
Unable to read file

### ISSUE THREAD

**Issue by saurabh-nichi** [rap2hpoutre/fast-excel#128]
Could not open /tmp/php6R4Wdr for reading! (Could not open /tmp/php6R4Wdr for reading.)

`function readData(Request $request) { return (new FastExcel())->import($request->file('itemFile')); }`

**Comment by rap2hpoutre** [comment]
Hi @saurabh-nichi, thank you for contributing. You can check these issues: https://github.com/rap2hpoutre/fast-excel/issues/18 & https://github.com/rap2hpoutre/fast-excel/issues/57
