### ISSUE TITLE
How to get header's existence on xlsx import?

### ISSUE THREAD

**Issue by suicodave** [rap2hpoutre/fast-excel#129]
I am making an upload records feature wherein I have to check the field's existence before iterating each row if such field is missing then the app has to throw an exception that the field is missing or misspelled and discard the whole import process.

I couldn't find an api like this:

```php
$excelFile->getHeaders();
```

**Comment by rap2hpoutre** [comment]
Hi @suicodave, thank you for your contribution. Unfortunately, there is currently no way to access to headers.

**Comment by DeepayanMallick** [comment]
I also want to get the headers. Because sometimes we need to format the headers.
