### ISSUE TITLE
Throwing error if the modal is empty

### ISSUE THREAD

**Issue by inquisitive-stha** [rap2hpoutre/fast-excel#131]
If the modal is empty, its throwing error.

```
return (new FastExcel(Review::all()))->download('file.xlsx');
```
If `Review` modal is error its throwing error.

Could we export the excel file with just the header? or do no action. But, prevent app from throwing an error.

**Comment by rap2hpoutre** [comment]
Hi @inquisitive-stha, thank you for contributing! It has been fixed in v1.3.2 thanks to @johanrosenson 🙌
