### ISSUE TITLE
export with select not working

### ISSUE THREAD

**Issue by maxdevis** [rap2hpoutre/fast-excel#132]
hi,
my code is:
$filename = "file.xlsx"
$select = array('tipo_variante', 'id_variante', 'descrizione', 'forn_descr');
 $data = DB::table($table)->select($select)->whereNull("deleted_at")->get()->toArray();
(new FastExcel($result))->export($filename);
but my excel is blank;

any help?

**Comment by johanrosenson** [comment]
FastExcel does not support array as input, it expects either a Collection or Generator.

Your code will work if you remove `->toArray()`

**Comment by maxdevis** [comment]
honestly, I tried to remove toArray, but I export a white excel sheet.
this problem happens if I use DB instead of using the model directly.

Br
Max

Il dom 1 dic 2019, 10:19 Johan Rosenson <notifications@github.com> ha
scritto:

**Comment by johanrosenson** [comment]
I just tested with this code and it works great.

```php
$table = 'users';
	$filename = "file.xlsx";
	$select = array('id', 'name', 'email');
	$data = DB::table($table)->select($select)->get();
	(new FastExcel($data))->export($filename);
```

Could the error for you be that in your example you are storing the DB-result in `$data` but you are passing `$result` to FastExcel?

**Comment by maxdevis** [comment]
I'll do some tests and let you know.  for now I thank you, if everything
goes well I will close the ticket.

Br
Max

Il dom 1 dic 2019, 23:04 Johan Rosenson <notifications@github.com> ha
scritto:
