### ISSUE TITLE
how to use progress bar

### ISSUE THREAD

**Issue by Raymonsystem** [rap2hpoutre/fast-excel#133]
hi,

How to use progress bar in import ?

thank you.

**Comment by diegonella** [comment]
I have solved it using server events
https://limi.eu/projects/javascript/eventsource.html

**Comment by rap2hpoutre** [comment]
Hi @Raymonsystem, thank you for contributing! Unfortunately, here is no built-in progress bar in this lib. Still, you can use the solution posted by @diegonella.
