### ISSUE TITLE
Wrap values in quotations

### ISSUE THREAD

**Issue by dylannykolyszyn** [rap2hpoutre/fast-excel#134]
Hi, we've switched to this from Laravel Excel, but I've noticed that when I open a CSV file in a text editor, none of the values are wrapped in quotations. The only thing that's wrapped in quotes is the delimiter (",").

This is causing an issue for one of our third parties who we send exports to, is there any way to resolve this?

Thanks

**Comment by rap2hpoutre** [comment]
Hi @frosstic, thank you for your feedback! Actually, only the fields that _need_ to be quoted (because they contain delimiter characters) have quote. CSV could work like this. Do you have any issue by not quoting them all?

**Comment by frosstic** [comment]
Hi, we don't have any issues, from our perspective your tool works great,
and we've actually overcame the issue with our provider, but for future
reference is there any way to ensure all fields are wrapped in quotes, not
just the ones containing delimiters. Thanks!

**Comment by nosun** [comment]
Use fast-excel to generate google merchant feeds, which cannot be recognized by google merchant. but it is possible by using laravel-excel，Its related to this issue

**Comment by nosun** [comment]
https://csv.thephpleague.com/9.0/ support  this feather, the code as below:

```
<?php
use League\Csv\Writer;

$collection = [
    [1, 2],
    ['value 2-0', 'value 2-1'],
    ['to"to', 'foo\"bar'],
];

$writer = Writer::createFromString();
$writer->encloseAll(); //return false;
$writer->forceEnclosure();
$writer->encloseAll(); //return true;
$writer->insertAll($collection);
echo $writer->toString(), PHP_EOL;

// the CSV file will contain enclosed cell.
// Double quote are not added in presence of the 
// escape character as per PHP's CSV writing documentation

// "1","2"
// "value 2-0","value 2-1"
// "to""to","foo\"bar"
```
