### ISSUE TITLE
Failed to Import XLSX file

### ISSUE THREAD

**Issue by Binternet** [rap2hpoutre/fast-excel#14]
Trying to open a XSLX file:
```
$collection = (new \Rap2hpoutre\FastExcel\FastExcel)->import(storage_path('test.xlsx'));
dd($collection);
```

Throws this exception:
`Rap2hpoutre\FastExcel\FastExcel and Rap2hpoutre\FastExcel\Importable define the same property ($with_header) in the composition of Rap2hpoutre\FastExcel\FastExcel. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed`

**Comment by rap2hpoutre** [comment]
OK, sorry about that! What version of PHP do you use?

**Comment by Binternet** [comment]
5.6.32

**Comment by rap2hpoutre** [comment]
It works in 7.* but not in 5.6.*. Anyway, I fixed it! Could you try to update with `composer update` then test again?

**Comment by Binternet** [comment]
Boom! works like a charm! thanks
