### ISSUE TITLE
Fix missing PHP 7.4 for travis test

### ISSUE THREAD

**Issue by johanrosenson** [rap2hpoutre/fast-excel#141]
Is it possible to fix so that the PHP 7.4 test runs correctly so that the waiting PR's can be tested and possible merged? :)

Link where issue is visible: https://travis-ci.org/rap2hpoutre/fast-excel/builds/620766763

**Comment by rap2hpoutre** [comment]
Thank you for your feedback! It was an travis issue, it's fixed now. 👍 I will have a look at your PRs soon (sorry for the delay)
