### ISSUE TITLE
How to setting start row when import Excel?

### ISSUE THREAD

**Issue by binhnv56** [rap2hpoutre/fast-excel#147]
Fast excel always get the header as first row? but my excel file header is start in second row?
How to change start row when import?

**Comment by aminsbd1** [comment]
basic output of fast-excel is array data. 

you can improve that..

**Comment by rap2hpoutre** [comment]
Hi @binhnv56 & @aminsbd1 

You could have a look at this answer: https://github.com/rap2hpoutre/fast-excel/issues/102#issuecomment-497723008

Basically, you have to handle header yourself and ignore automatic header handling:


```php
$users = (new FastExcel)->withoutHeaders()->import('file.xlsx', function ($line) {
    // Skip if empty or first line (i.e. header), ... 
    // ... return the object otherwise (without the first columns)
});
```

**Comment by binhnv56** [comment]
> Hi @binhnv56 & @aminsbd1
> 
> You could have a look at this answer: [#102 (comment)](https://github.com/rap2hpoutre/fast-excel/issues/102#issuecomment-497723008)
> 
> Basically, you have to handle header yourself and ignore automatic header handling:
> 
> ```
> $users = (new FastExcel)->withoutHeaders()->import('file.xlsx', function ($line) {
>     // Skip if empty or first line (i.e. header), ... 
>     // ... return the object otherwise (without the first columns)
> });
> ```

Thank you for your confirmation. withoutHeaders() very helpful, my problem is resolve.
