### ISSUE TITLE
[Question] Cloud Storage Support

### ISSUE THREAD

**Issue by yoelpc4** [rap2hpoutre/fast-excel#153]
Do `fast-excel` able to export excel to cloud storage e.g: s3 or cloudinary?

**Comment by rap2hpoutre** [comment]
Hi @yoelpc4, thank you for your feedback (and sorry for late answer!).

You could write data to a file or to a PHP stream. I'm not sure but I guess you could do something with stream and S3 file storage (https://laravel.com/docs/7.x/filesystem). Or maybe you could save it locally then send it to s3:


```php
// pseudo-code (untested)
(new FastExcel($users))->export('file.xlsx');
Storage::disk('s3')->put('file.xlsx', file_get-contents('file.xlsx));
```

**Comment by yoelpc4** [comment]
I've been tried and it can be uploaded to cloud storage after successfully exported
