### ISSUE TITLE
Event to export/download is possible?

### ISSUE THREAD

**Issue by gabrielchiron** [rap2hpoutre/fast-excel#154]
Hi!
Its posible to use a callback to send email or notify with laravel? Like event to hook any function.

All its work propertly but i need send email when the .csv is download or when csv is generated :)

**Comment by rap2hpoutre** [comment]
Hi @gabrielchiron. Thank you for your contribution! 

Since export is done sequentially, you could send a mail at the end tof the process by using Laravel mail feature: https://laravel.com/docs/7.x/mail#sending-mail

So you could do something like this:
```
fastexcel($collection)->export('file.xlsx');
Mail::to($user)->send(new CollectionExported());
```
