### ISSUE TITLE
ERR_INVALID_RESPONSE when exporting excel for download if the dataset is too large

### ISSUE THREAD

**Issue by matrixhcl** [rap2hpoutre/fast-excel#156]
OS: linux alpine (in docker)
php ver: 7.2

I have a function which basically turns a query result to a cursor, and simply pass it to FastExcel to turn the query result into xlsx file for user to download.

>
    public function exportAssignmentReport(Request $request)
    {
        $dataSource = self::getReportAssignmentList($request, true)->cursor(); // the function returns a query builder
        $result = function () use ($dataSource) {
            foreach ($dataSource as $row) {
                yield new ReportAssignmentListResource($row); //laravel resource class is used for formatting the data
            };
        };
        return (new FastExcel($result()))->download('AssignmentReport.xlsx');
    }

When the query result is small (around 10000 records) it works perfectly fine. Unfortunately, when the query result is around 30000 records, it fails randomly, and the browser shows error below:
![image](https://user-images.githubusercontent.com/17959517/76957710-42ab2000-6951-11ea-99e5-7de70813a393.png)

I have checked the nginx log and laravel log, seems no error was logged when this error occurred.

**Comment by marcelloinfoweb** [comment]
The same problem.
