### ISSUE TITLE
Design a logo

### ISSUE THREAD

**Issue by rap2hpoutre** [rap2hpoutre/fast-excel#16]
Maybe a mix of laravel logo and excel logo.

**Comment by Tobaloidee** [comment]
Hi, i am a graphic designer and i can be of help to this issue. :)

**Comment by Tobaloidee** [comment]
Hello Sir @rap2hpoutre  here are my designs Sir! I made 2 variations & 2 colors  to choose from.
![fastexcel-09](https://user-images.githubusercontent.com/36028424/40173157-8096f8f8-5a03-11e8-8c41-228b7248caba.png)

# version 1

icons
![fastexcel-01](https://user-images.githubusercontent.com/36028424/40173192-965dda12-5a03-11e8-9e0a-50dae088f5cd.png)
![fastexcel-02](https://user-images.githubusercontent.com/36028424/40173193-969a4f42-5a03-11e8-8f4d-b05a0153a5b7.png)
logotype
![fastexcel-05](https://user-images.githubusercontent.com/36028424/40173202-9a03d68a-5a03-11e8-9968-6b7e3b4f8a1b.png)
![fastexcel-06](https://user-images.githubusercontent.com/36028424/40173203-9a4fcfea-5a03-11e8-82d9-f0a3e0720026.png)

# version 2

icons
![fastexcel-03](https://user-images.githubusercontent.com/36028424/40173222-b07c8718-5a03-11e8-8923-c9d54aecaf1f.png)
![fastexcel-04](https://user-images.githubusercontent.com/36028424/40173224-b0b70096-5a03-11e8-9cac-8f43cdd23b05.png)
logotype
![fastexcel-07](https://user-images.githubusercontent.com/36028424/40173230-b65b41ec-5a03-11e8-8727-4de56d7d06f9.png)
![fastexcel-08](https://user-images.githubusercontent.com/36028424/40173231-b6967000-5a03-11e8-8199-ff9913cef8bc.png)

if there's any modifications in mind just let me know

**Comment by Tobaloidee** [comment]
Both are great Sir..for me its the first veraion too..but you can't take your eyes away from that green..haha

**Comment by rap2hpoutre** [comment]
@Tobaloidee  I just tried something: https://github.com/rap2hpoutre/fast-excel/blob/3424cbcccdeac183a99d8edc4c550cf8091f8a0c/README.md

What do you think?

**Comment by Tobaloidee** [comment]
Looks very good Sir, I feel that you really like the other version too.. 😀

**Comment by Tobaloidee** [comment]
Hi Sir, how is it going? :)

**Comment by rap2hpoutre** [comment]
@Tobaloidee Have a look to the readme, it's included now! (maybe I will change later to "image only" version, not sure). I still have a few questions:

 - Do you have a twitter account? (I would like to credit you).
 - Do you have a [patreon](https://www.patreon.com/) or something similar? I would like to support you for your awesome work.
 - Could you put somewhere a zip or something similar with the different version of the images? I will try to keep it somewhere for later use.

Feel free to ask me anything!

... Again, thank you so much!!

**Comment by Tobaloidee** [comment]
Hi Sir, that looks awesome!:)  Do you have an email address? i'll post here the link to my google drive for all the other versions of the designs.

**Comment by Tobaloidee** [comment]
Here is the link to my drive Sir.. I can make a pull request and put the SVG & PNG files if you want.

[FASTEXCELfiles](https://drive.google.com/drive/u/0/folders/1xq7YIlUuaTp0PrBPcp7NhmYNwywnvpmu)

**Comment by rap2hpoutre** [comment]
Thank you! I've just downloaded the files and I will find a solution to store it somewhere accessible via the repository. If you have any question or request, you can find my email address is here: https://github.com/rap2hpoutre/fast-excel/blob/master/composer.json#L27

**Comment by Tobaloidee** [comment]
Hi Sir..did you receive my email?

**Comment by rap2hpoutre** [comment]
@Tobaloidee Yes, I just sent you an answer! I close this issue now, it's fixed!
