### ISSUE TITLE
Laravel 7 not supported 

### ISSUE THREAD

**Issue by Jaspur** [rap2hpoutre/fast-excel#160]
All function called to the Facade are not working anymore  @rap2hpoutre:

```Call to undefined method Rap2hpoutre\FastExcel\Facades\FastExcel::export()```

**Comment by nycosborne** [comment]
How was this class being created and what line of code was causing the error. This seems to be working with Laravel 7. Could you provide a more comprehensive, might be a caching issue.

**Comment by rap2hpoutre** [comment]
Hi @Jaspur thank you for your contribution. I'm not sure I understand your problem. Could you post:
- the full error backtrace
 - the code that generates this error
 - Laravel version
 - fast-excel version
