### ISSUE TITLE
Usage with LazyCollection

### ISSUE THREAD

**Issue by DUBroquin** [rap2hpoutre/fast-excel#163]
Hi !

Is there a way to use Laravell 6|7 lazy collection as export dataset ?

**Comment by rap2hpoutre** [comment]
Hi @DUBroquin, thank you for your feedback! 

This could be great! I have written a [small demo using generators](https://dev.to/rap2hpoutre/export-10m-rows-in-xlsx-with-laravel-without-memory-issues-6bk) just before Laravel's lazy collection were released (or maybe I was not aware and it already existed). In other words you _could_ do something similar with generators, but not with the actual lazy collection. It should be possible to implement lazy collection integration though.

Example with generators:

```php
function usersGenerator() {
    foreach (User::cursor() as $user) {
        yield $user;
    }
}

// Export consumes only a few MB, even with 10M+ rows.
$users = usersGenerator();
fastexcel($users)->export('test.xlsx');
```

Larger slices:

```php
// Generator function
function getUsersOneByOne() {
    // build your chunks as you want (200 chunks of 10 in this example)
    for ($i = 0; $i < 200; $i++) {
        $users = DB::table('users')->skip($i * 10)->take(10)->get();
        // Yield user one by one
        foreach($users as $user) {
            yield $user;
        }
    }
}

// Export consumes only a few MB
(new FastExcel(getUsersOneByOne()))->export('test.xlsx');
```

Let me know if you feel like it could help you. Anyway, we have to think about Lazy Collection integration!

**Comment by johanrosenson** [comment]
@DUBroquin @rap2hpoutre 

Unless i'm totally mistaken now i believe that support for LazyCollections do not need to be implemented in FastExcel.
It is possible to use the method  `getIterator()` to get the underlying iterator from a LazyCollection.

example:
```
(new FastExcel($lazyCollection->getIterator()))->export('secrets.xlsx');
```

**Comment by joshbaumann** [comment]
Using the `lazy` method  on a query builder instance will also work.

```
function resultsGenerator(Builder $query) {
    yield from $query->lazy();
}
```

```
(new FastExcel(resultsGenerator($query))->export(....
`````

**Comment by ssaaiidd** [comment]
@johanrosenson  @joshbaumann , Do you have a workaround suggestion for using LazyCollection on import?
