### ISSUE TITLE
Call to undefined method stdClass::toArray() at  fast-excel/src/Exportable.php:176

### ISSUE THREAD

**Issue by Dumpp** [rap2hpoutre/fast-excel#165]
Hye there,
I am getting the following error while trying to download the Excel file.

$list = DB::table('users')
->join('wup', 'users.id', '=', 'wup.user_id')
->join('w', 'wup.w_id', '=', 'w.id')
->select('users.name as Name', 'w.title As Title','w.link  as w URL','w.access_code As Access Code', 'users.email as Email','users.phone as Phone','users.city as City')
->where('w.id',$id)
->get()->toArray();
$list = collect($data);
return (new FastExcel($list))->download('file.xlsx'); 

It works If the SQL statement returns 100+ rows  but when it returns less than 10, It's not working,

Call to undefined method stdClass::toArray() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method stdClass::toArray() at /home/q5sfgux4pi37/public_html/vendor/rap2hpoutre/fast-excel/src/Exportable.php:176)
[stacktrace]
#0 /home/q5sfgux4pi37/public_html/vendor/rap2hpoutre/fast-excel/src/Exportable.php(134): Rap2hpoutre\\FastExcel\\FastExcel->writeHeader(Object(Box\\Spout\\Writer\\XLSX\\Writer), Object(stdClass))
#1 /home/q5sfgux4pi37/public_html/vendor/rap2hpoutre/fast-excel/src/Exportable.php(104): Rap2hpoutre\\FastExcel\\FastExcel->writeRowsFromCollection(Object(Box\\Spout\\Writer\\XLSX\\Writer), Object(Illuminate\\Support\\Collection), NULL)
#2 /home/q5sfgux4pi37/public_html/vendor/rap2hpoutre/fast-excel/src/Exportable.php(71): Rap2hpoutre\\FastExcel\\FastExcel->exportOrDownload('file.xlsx', 'openToBrowser', NULL)
#3 /home/q5sfgux4pi37/public_html/vendor/symfony/http-foundation/StreamedResponse.php(112): Rap2hpoutre\\FastExcel\\FastExcel->Rap2hpoutre\\FastExcel\\{closure}()
#4 /home/q5sfgux4pi37/public_html/vendor/symfony/http-foundation/Response.php(381): Symfony\\Component\\HttpFoundation\\StreamedResponse->sendContent()
#5 /home/q5sfgux4pi37/public_html/public/index.php(58): Symfony\\Component\\HttpFoundation\\Response->send()
#6 {main}

**FYI 
"php": "^7.1.3",
"laravel/framework": "5.8.*",
"rap2hpoutre/fast-excel": "^1.7"**	

ScreenShot: https://prnt.sc/rxfz89
Thank you In Advance

**Comment by rap2hpoutre** [comment]
Hi @Dumpp thank you for contributing! Could you check what's inside `$list` when it fails? You could use `dd()`:

```php
// ...
$list = collect($data);

dd($list);
```
