### ISSUE TITLE
change the width of the columns

### ISSUE THREAD

**Issue by crisfalt** [rap2hpoutre/fast-excel#168]
is it possible to change the width of the columns for export to excel?

**Comment by elminson** [comment]
You can check this PR https://github.com/box/spout/pull/715 not sure if they will merge it but you can take a look

**Comment by rap2hpoutre** [comment]
Thanks @elminson  🙏 

@crisfalt It's currently not possible. This package is based on Spout which can not handle this need. See: box/spout#129 & box/spout#715

**Comment by rap2hpoutre** [comment]
https://github.com/rap2hpoutre/fast-excel/issues/119
