### ISSUE TITLE
Format date during export excel file

### ISSUE THREAD

**Issue by BiliBabu** [rap2hpoutre/fast-excel#169]
Hello,

Iv'e successfully formatted numbers when I export the excel file.
I can't seem to get the date to be formatted as date in excel and not as a string.

Does anybody as any implementation for that?
for example.
21/01/2020 is presented as '21/01/2020 that ' is presenting it as string and not date.
21-01-2020 is '21-01-2020 etc...

**Comment by rap2hpoutre** [comment]
Hi @BiliBabu & @accedotech 👋 , thank you for your contribution. This library is based on spout, it seems it is possible to format date for import but not for export: https://opensource.box.com/spout/docs/#datetime-formatting 

Unfortunately, I don't have any workaround right now :/

**Comment by BiliBabu** [comment]
I found a work around.
I export the file as csv didn't try as xls.
Then during export I formated the dates manually in php.
Example:
$dateValue == null ? "" : date("d/m/Y", strtotime($dateValue ))

If date value is set to date in SQL then the date will be formatted to d/m/Y, you can choose which fromat via date function from php.
