### ISSUE TITLE
After exporting, the number is stored as string in Excel

### ISSUE THREAD

**Issue by enaeim** [rap2hpoutre/fast-excel#170]
PHP version: 7.2.4
Laravel version:  5.8.38
rap2hpoutre/fast-excel version: 1.7.0

Hi.
1. After exporting, the number is stored as string in Excel. While I want numbers to be stored in numeric format in Excel.
2. How do I style Excel output? Such as color, thickness, align, etc.
Please help me.
Thanks.

**Comment by NazarAli** [comment]
i have same problem

**Comment by leexin** [comment]
Have the same issue. Need to store numbers as numeric field in Excel.

**Comment by elminson** [comment]
For format, you can check this PR https://github.com/rap2hpoutre/fast-excel/pull/161/files

**Comment by rap2hpoutre** [comment]
> After exporting, the number is stored as string in Excel. While I want numbers to be stored in numeric format in Excel.

It has been released in v2.0.0 thanks to @dukferradj 🎉  (see: https://github.com/rap2hpoutre/fast-excel/pull/166) cc @leexin @NazarAli @enaeim
