### ISSUE TITLE
How i can setup $maxNumStringsPerTempFile for spout via fastexcel

### ISSUE THREAD

**Issue by Zigman13** [rap2hpoutre/fast-excel#172]
Sorry for dumb question, but how i can setup option for spout maxNumStringsPerTempFile for \box\spout\src\Spout\Reader\XLSX\Helper\SharedStringsCaching\FileBasedStrategy via fastexcel options ?

**Comment by rap2hpoutre** [comment]
Related: https://github.com/rap2hpoutre/fast-excel/issues/162

**Comment by rap2hpoutre** [comment]
Closed as duplicate
