### ISSUE TITLE
ErrorException fopen(/var/www/html/laravel7/storage/app/reports/rides_list/2020-05.csv): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by carlosh1989** [rap2hpoutre/fast-excel#173]
```
 $month_file_path_2 = storage_path('app').'/'.$month_file_path;
 (new FastExcel($this->usersGenerator($data)))->export($month_file_path_2);
```

No folder or file will be created in storage / app /

**Comment by Phoenix3264** [comment]
how to install in laravel7? always getting error like :
Problem 1
    - xethron/migrations-generator v2.0.0 requires way/generators dev-feature/laravel-five-stable -> no matching package found.
    - Conclusion: remove laravel/framework v7.19.0

**Comment by rap2hpoutre** [comment]
Hi @carlosh1989 Thank you for your feedback! Does the folder already exist? It should exist before creating the file.
