### ISSUE TITLE
Laravel 5.3 isn't actually Supported fully

### ISSUE THREAD

**Issue by jacobjlandry** [rap2hpoutre/fast-excel#175]
This library uses a helper function "blank()" that isn't included until Laravel 5.5
The composer allows support as low as Laravel 5.3, however.
Anyone using 5.3 or 5.4 will receive an error that "blank()" does not exist until they create it themselves.

Can you include the "blank" function with the library or provide an alternative for lower versioned platforms that you support?

```
**
 * Determine if the given value is "blank".
 *
 * @param  mixed  $value
 * @return bool
 */
function blank($value)
{
    if (is_null($value)) {
        return true;
    }

    if (is_string($value)) {
        return trim($value) === '';
    }

    if (is_numeric($value) || is_bool($value)) {
        return false;
    }

    if ($value instanceof Countable) {
        return count($value) === 0;
    }

    return empty($value);
}
```

**Comment by rap2hpoutre** [comment]
Thank you for your feedback!

Available in v2.1.0
