### ISSUE TITLE
set number to numericvalue

### ISSUE THREAD

**Issue by zieru** [rap2hpoutre/fast-excel#176]
how to make number as numeric column ?

**Comment by rap2hpoutre** [comment]
Hi @zieru Thank you for your feedback. What version do you use? It seems the problem has been resolved in v2. Could you try to update to latest version?

Source: https://github.com/rap2hpoutre/fast-excel/pull/166 & https://github.com/rap2hpoutre/fast-excel/issues/170

**Comment by rap2hpoutre** [comment]
Resolved
