### ISSUE TITLE
Could not open file to import

### ISSUE THREAD

**Issue by robertnicjoo** [rap2hpoutre/fast-excel#18]
I cannot read my imported file, here is my function:

```php
 public function import(Request $request)
    {
        $products = (new FastExcel)->import($request->file('file'), function ($reader) {
            return Product::create([
                'title' => $reader['title'],
                'slug' => $reader['slug'],
                'imageOne' => $reader['imageOne'],
                'imageTwo' => $reader['imageTwo'],
                'imageThree' => $reader['imageThree'],
                'short_description' => $reader['short_description'],
                'description' => $reader['description'],
                'stock' => $reader['stock'],
                'price' => $reader['price'],
                'installation_price' => $reader['installation_price'],
                'meta_description' => $reader['meta_description'],
                'meta_tags' => $reader['meta_tags'],
                'discounted_price' => $reader['discounted_price'],
                'start_discounted' => $reader['start_discounted'],
                'end_discounted' => $reader['end_discounted'],
                'demo_link' => $reader['demo_link'],
                'status' => $reader['status'],
                'category_id' => $reader['category_id']
            ]);
        });

        Session::flash('success', 'Your products imported successfully.');
    }
```

error i get:

```html
Could not open C:\Users\usename\AppData\Local\Temp\php32D9.tmp for reading! (Could not open C:\Users\usename\AppData\Local\Temp\php32D9.tmp for reading.)
```

PS: I have tried documents way: using `return Product::create(['title' => $reader['title'],........` instead of foreach, `same result (same error).

any idea?

**Comment by rap2hpoutre** [comment]
Thanks for your contribution!

You could try this (save the file in storage, **then** import the file):

```php
 public function import(Request $request)
    {
        $path = $request->file('file')->store('excel-files');
        $products = (new FastExcel)->import($request->file($path), function ($reader) {
            return Product::create([
                'title' => $reader['title'],
                'slug' => $reader['slug'],
                'imageOne' => $reader['imageOne'],
                'imageTwo' => $reader['imageTwo'],
                'imageThree' => $reader['imageThree'],
                'short_description' => $reader['short_description'],
                'description' => $reader['description'],
                'stock' => $reader['stock'],
                'price' => $reader['price'],
                'installation_price' => $reader['installation_price'],
                'meta_description' => $reader['meta_description'],
                'meta_tags' => $reader['meta_tags'],
                'discounted_price' => $reader['discounted_price'],
                'start_discounted' => $reader['start_discounted'],
                'end_discounted' => $reader['end_discounted'],
                'demo_link' => $reader['demo_link'],
                'status' => $reader['status'],
                'category_id' => $reader['category_id']
            ]);
        });

        Session::flash('success', 'Your products imported successfully.');
    }
```

See: https://github.com/box/spout/issues/448, https://github.com/box/spout/issues/286, https://github.com/box/spout/issues/379 and https://github.com/box/spout/issues/294.

If it does not work, could you try using a full path for your file? Something like "C:/.../.../file/form.xlsx"
There must be something wrong with how Spout handles path on Windows.

**Comment by robertnicjoo** [comment]
the code gives
```html
Could not open for reading! File does not exist.
```
I also tried:

```php
$path = "file:///C:/Users/username/Downloads/new/new-products.csv";
```
and i got the same error:

```html
Could not open for reading! File does not exist.
```

as the result of saving my file to storage I have `txt` file in my storage folder included this content  `, , , , , ,`

**Comment by rap2hpoutre** [comment]
My code was wrong, could you try this:

```php
 public function import(Request $request)
    {
        $path = $request->file('file')->store('excel-files');
        $products = (new FastExcel)->import(storage_path('app/' . $path), function ($reader) {
            return Product::create([
                'title' => $reader['title'],
                'slug' => $reader['slug'],
                'imageOne' => $reader['imageOne'],
                'imageTwo' => $reader['imageTwo'],
                'imageThree' => $reader['imageThree'],
                'short_description' => $reader['short_description'],
                'description' => $reader['description'],
                'stock' => $reader['stock'],
                'price' => $reader['price'],
                'installation_price' => $reader['installation_price'],
                'meta_description' => $reader['meta_description'],
                'meta_tags' => $reader['meta_tags'],
                'discounted_price' => $reader['discounted_price'],
                'start_discounted' => $reader['start_discounted'],
                'end_discounted' => $reader['end_discounted'],
                'demo_link' => $reader['demo_link'],
                'status' => $reader['status'],
                'category_id' => $reader['category_id']
            ]);
        });

        Session::flash('success', 'Your products imported successfully.');
    }
```

The only line I changed is this one:

```
$products = (new FastExcel)->import(storage_path('app/' . $path), function ($reader) {
```

It should work!

**Comment by robertnicjoo** [comment]
it says:

```html
Could not open C:\laragon\www\mynewsite\storage\app/excel-files/WXgZu1J2fgSVDP2pkoaI8Dh0Z7fqUq40ymuiFQTC.txt for reading! File does not exist.
```

**Comment by pankajvasnanitech123** [comment]
I want to know if the user is uploading the excel file and I dont want to store the file in storage. Is there a solution for this ?

**Comment by rap2hpoutre** [comment]
@robertnicjoo Sorry for late answer (vacations). 

Could you test with this CSV file: https://github.com/rap2hpoutre/fast-excel/blob/master/tests/test2.csv? It's the one used in my unit tests (and the unit tests actually works).

I tested your CSV (https://github.com/rap2hpoutre/fast-excel/blob/master/tests/test18.csv) and added a unit test (https://github.com/rap2hpoutre/fast-excel/blob/master/tests/FastExcelTest.php#L163) and it still works.

So, I don't think it's a problem about your CSV content.

I think the problem may be about your file extension. **Could you rename your file to something.csv?** And could you double check the uploaded file does exists in the folder you open?

**Comment by Harti** [comment]
I ha**d** the same issue with files not opening.  At first I thought it was because I still had the file open, but then I realized I was using `.xls` which is a tad different from `.xlsx` and [not supported by Spout](https://github.com/box/spout/issues/213). 

**If you are looking to import XLS, look into using [unoconv](https://softwarerecs.stackexchange.com/questions/4400/php-library-to-transform-excel-xls-xlsx-to-opendocument-ods) to convert the file to XLSX first.**


@rap2hpoutre thanks for making this lib! With your main competitor having dropped importing with his 3.0 version, this is pretty much the only viable solution.

Importing your test CSV file, however, I'm getting the following error (package v0.2):

``` 
php artisan forestmanager:import storage/test2.csv -v

   ErrorException  : array_combine(): Both parameters should have an equal number of elements

  at /var/www/vendor/rap2hpoutre/fast-excel/src/Importable.php:69
    65|                     }
    66|                     if ($count_header > $count_row = count($row)) {
    67|                         $row = array_merge($row, array_fill(0, $count_header - $count_row, null));
    68|                     }
  > 69|                     $collection[] = $callback ? $callback(array_combine($headers, $row)) : array_combine($headers, $row);
    70|                 }
    71|             } else {
    72|                 foreach ($sheet->getRowIterator() as $row) {
    73|                     $collection[] = $row;

  Exception trace:

  1   array_combine()
      /var/www/vendor/rap2hpoutre/fast-excel/src/Importable.php:69

  2   Rap2hpoutre\FastExcel\FastExcel::import("storage/test2.csv", Object(Closure))
      /var/www/app/Console/Commands/ImportAppDatabase.php:50
``` 


Command:
```
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Rap2hpoutre\FastExcel\FastExcel;

class ImportAppDatabase extends Command
{

    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'forestmanager:import {file}';

    ...

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $file = $this->argument('file');

        $import = (new FastExcel)->import($file, function($line)
        {
             // left empty for the time being
        });
    }
}

```

**Comment by rap2hpoutre** [comment]
@Harti Thank you for contributing!

> If you are looking to import XLS, look into using unoconv to convert the file to XLSX first.

I did not know this application, thanks! (still I will not include it in the package, since it's an executable file)

About your CSV test, I don't understand why you have a problem because it's already unit tested here: https://github.com/rap2hpoutre/fast-excel/blob/master/tests/FastExcelTest.php#L46

```php
public function testImportCsv()
{
    $original_collection = $this->collection();

    $collection = (new FastExcel())->import(__DIR__.'/test2.csv');
    $this->assertEquals($original_collection, $collection);

    // ...
}
```

**Comment by Harti** [comment]
@rap2hpoutre did you unit-test it under PHP 7.2? 

They changed a lot of core function parameters so that they are no longer duck-typed but _have to_ implement certain core interfaces. For the `count()` function, this would be `Countable` - `count(null)` will cause a PHP warning.

From the error message, it looks like something's off with `array_combine()` here. I can't investigate this, all I know is that your test2.csv file throws an error for me.

**Comment by rap2hpoutre** [comment]
@Harti 

> did you unit-test it under PHP 7.2?

Yes!

Version:
```bash
➜  laravel-fast-excel git:(master) php -v
PHP 7.2.1 (cli) (built: Jan  5 2018 17:34:14) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
```

```bash
➜  laravel-fast-excel git:(master) phpunit
PHPUnit 7.0.2 by Sebastian Bergmann and contributors.

Error:         No code coverage driver is available

.........                                                           9 / 9 (100%)

Time: 275 ms, Memory: 10.00MB

OK (9 tests, 12 assertions)
```

Could you try to run the unit tests?

**Comment by mountainguan** [comment]
I also meet the same error.

**Comment by rap2hpoutre** [comment]
Hi @mountainguan, thank you for contributing!

> I also meet the same error.

What do you mean by "the same error"? I feel like there are different errors in this issue, and I'm not sure which one is yours!

1. if it's [this one](https://github.com/rap2hpoutre/fast-excel/issues/18#issue-317061563), could you try the code posted [here](https://github.com/rap2hpoutre/fast-excel/issues/18#issuecomment-384069693)?
2. If it's [this one](https://github.com/rap2hpoutre/fast-excel/issues/18#issuecomment-384069693), could you try to run the unit tests?

**Comment by mountainguan** [comment]
@rap2hpoutre could not read xls file...

**Comment by mountainguan** [comment]
@rap2hpoutre yeah,I finally go to use laravel-excel 2.1 version.

**Comment by codescamz** [comment]
@robertnicjoo u can use base_path() for mayor control.
[https://laravel.com/docs/5.7/helpers#paths](url)

**Comment by mikizdr** [comment]
Why publish not well tested packages? If you want the audience test your package it would be polite to say that in description. Otherwise a lot of people implement package, then dive into problems, debugging, brainstorming and waist a lot of time trying to get result but finally without success. Your work is good and go on with that but have a respect to other times and trust.

**Comment by rap2hpoutre** [comment]
@mikizdr Sorry for hurting you. What is wrong? What about your actual problem?

**Comment by luisfergago** [comment]
Got the same problem, i think its because we are not saving the file in our storage but processing it directly from upload, when you check the .csv file object it doesnt show the type of file....

well, thats my guessing :)

![image](https://user-images.githubusercontent.com/20917611/58726315-a94d5600-839e-11e9-884c-fb8597d33c29.png)

**Comment by mikizdr** [comment]
File is stored properly and it exists. Maatwebexcel can read and handle that file but FastExcel can't. It says:

> Could open the file ....path + filename.xlsx for reading!

Path is under /storage/app/uploads/.... but for maatweb I'm using just /uploads/date/... and it works, with this package not. I tried everything but I don't know if it uses relative or abs path or some other conventions.
BTW: I'm trying this package to see if it can handle a huge xlsx file for importing to the db.

**Comment by rap2hpoutre** [comment]
With FastExcel, there is no pre-conf nor magic in specifying file path. You are free to import from any path you want, so you just have to write it:

```php
(new FastExcel)->import('/full/path/to/my/file.xlsx');
// or ...
(new FastExcel)->import('../relative/path/from/where/you/are.xlsx');
// or ...
(new FastExcel)->import(storage_path('app/uploads/date/file.xlsx')); // You want this one
// or ...
(new FastExcel)->import(base_path('data/file.xlsx'));
```

Let me know if it fixes your problem

**Comment by rap2hpoutre** [comment]
@mikizdr Let me know if I can close this issue :)

**Comment by bony1993** [comment]
@rap2hpoutre  i am using this package for excel import. now i need to view the title of excel file, how this possible with this package?

**Comment by klukiyan** [comment]
This issue is closed long time ago. But just in case somebody else will be coming accross it.
I had the same error message "Couldn't open for reading". After trying with firstly save file on server and then open - I discovered that Large files were simply not saved. There was `php_max_upload_filesize = 2MB` on my server's ini. Changed it to 2Gb and it started working very nice
