### ISSUE TITLE
Styles to row depending on the value of a column

### ISSUE THREAD

**Issue by Jgonz2140** [rap2hpoutre/fast-excel#182]
How can I apply different styles to each row?

I want to change the color of the row depending on the value, example: if I have a list of products and its existence is 0, put the row in red.

**Comment by rap2hpoutre** [comment]
Hi @Jgonz2140 thank you for your feedback! There is currently now way to style only one row. The only thing you can do is styling all rows (except header row) or header row. Source: https://github.com/rap2hpoutre/fast-excel#add-header-and-rows-style. However, it should be a good addition to this library!
