### ISSUE TITLE
The number in the cell is formatted as text

### ISSUE THREAD

**Issue by inquisitive-stha** [rap2hpoutre/fast-excel#183]
I am exporting using Fast Excel, however, it is showing this warning `The number in the cell is formatted as text ... `. I tried by casting the text to `intval` and `floatval` but still the same issue. Is there any way to set the column as number, like `setColumnFormat` in laravel-excel.

**Comment by rap2hpoutre** [comment]
Hi @inquisitive-stha thank you for your feedback, and sorry for late answer! It has been fixed in version 2.0. Could you try to update to the latest version?

**Comment by inquisitive-stha** [comment]
Should I use `intval` and `floatval` for that one or do we have features like `setColumnFormat` to set it. Could you link the docs if there is any for this case?

**Comment by vodela** [comment]
for datetime value its appending the single quote in excell cell, could you please suggest how to fix

**Comment by inquisitive-stha** [comment]
It should not add a single quote on a date, maybe you are adding it in code.

**Comment by vodela** [comment]
in the code iam not appending single quote, but the package is appending the single quote for YYYY-mm-dd H:i:s formatted date

**Comment by MoreiraJ-Prodigentia** [comment]
I'm in version 3.0 and this issue still occurs for me on dates.

> It should not add a single quote on a date, maybe you are adding it in code.

**Comment by rap2hpoutre** [comment]
Could you try with 5.3?

**Comment by shuraluka** [comment]
I'm using version 5.3.0 and the problem from the first sweat continues

**Comment by InforPsico** [comment]
Hi, I'm having the same problem and I'm using 5.4.
Is it closed without being resolved? If there's a way to format the cell as a number instead of text, please let me know where it's formatted. Otherwise, I'll have to consider using another package since they're requiring the cell to be numeric.
