### ISSUE TITLE
Is there a way to add a clickable column or cell with hyperlink?

### ISSUE THREAD

**Issue by GaboIV** [rap2hpoutre/fast-excel#184]

**Comment by rap2hpoutre** [comment]
Hi @GaboIV 👋 thank you for your feedback. I guess this is something that you could configure after exporting directly in your spreadsheet reader (e.g Microsoft Excel). This package exports strings and numbers, then you can format things the way you want after exporting. Let me know if it fixes your problem!

**Comment by GaboIV** [comment]
Thanks
