### ISSUE TITLE
Leading zeroes (0) gets removed

### ISSUE THREAD

**Issue by AniketKhadye8383** [rap2hpoutre/fast-excel#188]
Hey!

I'm having problem with "Leading Zeros". I am exporting a CSV files, where 1 column contains Phone Number, starting with "0", for example 06601234567.
How can I format this column as a string, so the leading zero doesn't get removed?

**Comment by rap2hpoutre** [comment]
Could you try to cast your variable to a string before exporting it? You could try something like this:

```php
$users = User::all();

foreach ($user as $users) {
  $user->phone = (string)$user->phone;
}

fastexcel($users)->export('file.xlsx');
```

If it still does not work there may be a problem with `phone` property before exporting. Could you try to dump a phone property _just before_ exporting?

```
dd($users->first()->phone)
```

**Comment by alvintheodora** [comment]
Hi @rap2hpoutre @AniketKhadye8383  , any progress for this one? My library version is v2.5.0. But still encounter this issue where leading zero gets removed, eventhough when I dd() the data passed is string.
Thank you in advance

**Comment by riaanjfox** [comment]
+1 Up - any feedback on this?
