### ISSUE TITLE
Sloooooow Exports

### ISSUE THREAD

**Issue by zhxscript** [rap2hpoutre/fast-excel#189]
I have a question, I have set this up hoping exporting would be faster, but I am finding that there is something that is just slow in the process.... It is taking sometimes 30+ Minutes to process 1200 records to export

I run this job in the background, as server command

`
 (new FastExcel($this->getClicksOneByOne($query)))
                ->headerStyle($header_style)
                ->export($this->job_data['file_path']);

    function getClicksOneByOne($click_records) {
            foreach($click_records->cursor() as $click) {
                yield $this->map($click);
            }
    }
`
$this->map, maps the data from the query into the proper column, while also returning a readable text header rather then the column name...

When it's done doing its thing, it makes it available for download on the dashboard and emails the user the file....

Everything works fine, except how long it is taking... and I really do not know why... especially for a puny number like 1200 records.

I also tried on the same record set, not using the generator, same result, I even tried it without the map function with no changes in the time to actually generate.

I do not believe this is a memory issue, as I watch memory usage during execution, remain within my server normal numbers. and no errors are throw/recorded and eventually the job usually does finish.

Anyone have some ideas?

**Comment by jstoone** [comment]
That does sound strange. Would you be able to share a simplified/anonymised sample or schema of the data, as well as what's within your `map()`-method? It could be that you're querying the database within the loop or something similar.

**Comment by rap2hpoutre** [comment]
Hi @zhxscript thank you for your feedback!

> I also tried on the same record set, not using the generator, same result, I even tried it without the map function with no changes in the time to actually generate.

I'm curious about this actual version of your code (without `map` function and not using generators): it seems this version could be a good candidate for understanding the problem and debugging. This package has been designed to be fast (hopefully), so I would like to understand in which circumstances it becomes slow. I would have suspected the `map` function (as suggested by @jstoone 🙏 ) or the usage of the generator, but you wrote that the problem still occurs without these two potential culprits.

Could you post the whole code of your simplified version that is still slow?

**Comment by zhxscript** [comment]
@jstoone @rap2hpoutre 

Thanks for the responses... So I finally was able to do some debugging that yielded some clues.. After clearing out all my queues and jobs, and walking away for a day,  I refactored to a simplified version, and it was blazing fast... no generator, no mapping.

I put my mapping function back in (without Generator), and there we have it, the issue... but why. 
For a very small number of 1200 or so records, i would expect a slight delay over a simplified version, BUT over 40 Minutes?

About my server:
The server only has 4GB of ram, but the max it ever reaches is 1.2GB, with memory allowance for PHP. This is why i do not believe more memory would make a difference here. 
2 Cores - Never any real load

This is the mapping function, seeing it seems to be the issue:
`
    public function map($clicks): array
    {
        $field_data = null;
        $mappings = [];

        foreach(array_merge($this->job_data['select'], $this->job_data['meta']) as $fields){

            switch($fields){
                case 'app_id':
                    if(!$clicks->app){
                        $field_data = 'App Removed';
                    }else{
                        $field_data = $clicks->app->app_name;
                    }
                    break;
                case 'offer_cpi':
                    $field_data = $clicks->offer_payout;
                    break;
                case 'publisher':
                    if(!$clicks->publisher){
                        $field_data = 'Publisher Removed';
                    }else{
                        $field_data = $clicks->publisher->getFullName();
                    }
                    break;
                case 'termed_date':
                    switch($clicks->status){
                        case ClickTrackingStatusEnum::CLOSED:
                            $field_data = $clicks->noncredit_date;
                            break;
                        default:
                            $field_data = null;
                    }
                    break;
                case 'credit_date':
                    switch($clicks->status){
                        case ClickTrackingStatusEnum::COMPLETE:
                        case ClickTrackingStatusEnum::REVERSE:
                            $field_data = $clicks->credit_date;
                            break;
                        default:
                            $field_data = null;
                    }
                    break;
                case 'noncredit_date':
                    switch($clicks->status){
                        case ClickTrackingStatusEnum::REVERSE:
                            $field_data = $clicks->noncredit_date;
                            break;
                        default:
                            $field_data = null;
                    }
                    break;
                case 'created_at':
                    switch($clicks->status){
                        default:
                            $field_data = $clicks->created_at;
                    }
                    break;
                default:
                    $field_data = $clicks->$fields;
            }

            $mappings[$this->headings($fields)] = $field_data;
        }

        return $mappings;
    }

    /**
     * @return array
     */
    public function headings($field)
    {
        return $this->field_titles[$field];
    }
`
*App and Publisher are available via loaded relationship

Again, once things actually do process, everything is fine, data is correct etc. If there is a better way to approach this I am open suggestions, but I need to have readable column titles and the formatted data..

Appreciate any and all feedback.

**Comment by jstoone** [comment]
@zhxscript congrats on getting it solved, good job. ☺️ :v:

I'll give your post and code examples a proper look over the weekend, and get back to you.

In the mean-time, I think we can go ahead and close the issue, no? Now that you've solved your issue, and the problem seemingly surfaced from your specific domain/implementation, rather than a bug in fast-excel.

**Comment by zhxscript** [comment]
@jstoone - Yes, this can be cloased, thanks for taking a look!

**Comment by jstoone** [comment]
@zhxscript you should be able to close the issue yourself. ✌️
