### ISSUE TITLE
Could not handle int/double value on export

### ISSUE THREAD

**Issue by andhikaribrahim** [rap2hpoutre/fast-excel#19]
Cannot export the #ref id (int) & correct_value (double)

Here's my code:

        $user = Auth::user();

        if (!empty($user->province_id) && $user->type == 2) {
            $data = DB::table('student')
            	->join('student_assesment', 'student_assesment.student_id', '=', 'student.id')
            	->select(
            		'student.id',
            		'student.code',
            		'student.first_name',
            		'student.last_name',
            		'student.phone',
            		'student_assesment.correct_value as correct_value'
            	)
                ->where('student.state', '!=', 4)
                ->where('student.province_id', $user->province_id)
                ->get();
        } elseif (!empty($user->district_id) && ($user->type == 3 || $user->type == 4)) {
            $data = DB::table('student')
            	->join('student_assesment', 'student_assesment.student_id', '=', 'student.id')
            	->select(
            		'student.id',
            		'student.code',
            		'student.first_name',
            		'student.last_name',
            		'student.phone',
            		'student_assesment.correct_value as correct_value'
            	)
                ->where('student.state', '!=', 4)
                ->where('student.district_id', $user->district_id)
                ->get();
        } else {
            $data = DB::table('student')
            	->join('student_assesment', 'student_assesment.student_id', '=', 'student.id')
            	->select(
            		'student.id',
            		'student.code',
            		'student.first_name',
            		'student.last_name',
            		'student.phone',
            		'student_assesment.correct_value as correct_value'
            	)
                ->where('student.state', '!=', 4)
                ->get();
        }

        $mappingData = $data->map(function($student) {
            return [
                "#Ref Id" => strval($student->id),
                "Kode" => $student->code,
                "Name" => $student->first_name . " " . $student->last_name,
                "Phone Number" => $student->phone,
                "Correct Answer" => strval($student->correct_value),
            ];
        });

        $export = (new FastExcel($mappingData))->download('export_result.xlsx');

        return $export;
    }

But when i set id & correct_value with `strval()` function, the data is exported.

any idea?

**Comment by rap2hpoutre** [comment]
Ok thank you for your contribution! This bug has to be fixed, I will try to tackle this issue soon.

**Comment by andhikaribrahim** [comment]
Glad to help! Also, is there any efficient way to export like 50-100k rows of data? In my case, i tried like chunking the query result with the Query Builder `chunk(n)` method. But it doesn't do much.

**Comment by rap2hpoutre** [comment]
@andhikaribrahim Could you open another issue for this need? Currently, this package does not allow data chunk, but it may be considered. Thanks again!

**Comment by rap2hpoutre** [comment]
Fixed via https://github.com/rap2hpoutre/fast-excel/commit/1f4112c9f52fa929976f33076a1c253eadbe673e. Available in v0.3.0!
