### ISSUE TITLE
Fresh laravel 8.19.0 Error installing fast-excel plugin

### ISSUE THREAD

**Issue by pixieaka** [rap2hpoutre/fast-excel#198]
PHP: 8.0.0
![image](https://user-images.githubusercontent.com/17777237/102511903-03e9f800-4092-11eb-9f4f-ff580f46035d.png)

**Comment by rap2hpoutre** [comment]
Fixed via https://github.com/rap2hpoutre/fast-excel/pull/201. Update to v2.3.0. Let me know if it fixes your issue!

**Comment by pixieaka** [comment]
@rap2hpoutre Fixed, Thanks :)
