### ISSUE TITLE
PHP8

### ISSUE THREAD

**Issue by georgeyeint** [rap2hpoutre/fast-excel#200]
On composer update/install with "require php 8.0" have an error:
"rap2hpoutre/fast-excel v2.2.0 requires php ^7.1 -> your php version (8.0.0) does not satisfy that requirement".
What can i do with it? Thank you.

**Comment by rap2hpoutre** [comment]
Fixed via https://github.com/rap2hpoutre/fast-excel/pull/201 available in v2.3.0
