### ISSUE TITLE
Always not respond when open excel files 

### ISSUE THREAD

**Issue by akechana** [rap2hpoutre/fast-excel#202]
Thank you so much for this package , i'm using laravel 5.8 and using rap2hpoutre/fast-excel latest version(2.30), when i download my model in excel files its always not respond  (see attached), please  advise  thanks.
![1609847548673](https://user-images.githubusercontent.com/45864077/103647774-66962b80-4f8e-11eb-98f4-54d45fc6a413.jpg)

**Comment by Spartaa** [comment]
how much data you are importing in excel ? and can you show me your code how you are doing this?
