### ISSUE TITLE
Download in ".xls"

### ISSUE THREAD

**Issue by sistemoc** [rap2hpoutre/fast-excel#204]
When exporting to ".xls", some software does not interpret correctly.
But exporting to ".xlsx" opens normal.

**Comment by rap2hpoutre** [comment]
Hi @sistemoc 👋  thank you for contributing. Unfortunately, FastExcel does not support XLS (only XLSX). If you need support for more formats, I would suggest using Laravel Excel: https://github.com/Maatwebsite/Laravel-Excel
