### ISSUE TITLE
How to send Excel with Guzzle post request?

### ISSUE THREAD

**Issue by jazz7381** [rap2hpoutre/fast-excel#205]
can i put return from "download('file.xlsx')" to Guzzle post request? with this code i'm not get anything

`$httpClient = new \GuzzleHttp\Client([
        'headers' => [
          'Authorization' => mdmTokenGenerate($token),
          'Accept' => 'application/json'
        ],
        'verify' => false
      ]);

      $response = $httpClient->post(
        "{$client->domain}/api/push", [
          'multipart' => [
            [
              'name' => 'file',
              'contents' =>  (new FastExcel(MasterNumbers::limit(1000)->get()))->download('file.xlsx')
            ]
          ]
        ]
      );`

**Comment by deanx3** [comment]
can you please tell how did you manage to do this ?

**Comment by deanx3** [comment]
@jazz7381
