### ISSUE TITLE
Import Validate Row before Insert Into Database

### ISSUE THREAD

**Issue by 9khaledSayed** [rap2hpoutre/fast-excel#207]
Hello i'm using fast-excel package for importing an excel file and insert it into database is there is a way to validate each row before the insertion?

**Comment by BrutusBossNL** [comment]
As documented in the "Quick Start", why not use it in the callback (which also provides per-line manipulation/editing)?

In the following example it is used to import/create an user in the database per line:
```php
$users = (new FastExcel)->import('file.xlsx', function ($line) {
    return User::create([
        'name' => $line['Name'],
        'email' => $line['Email']
    ]);
});
```
