### ISSUE TITLE
Export data in a horizontal format

### ISSUE THREAD

**Issue by mikeladon** [rap2hpoutre/fast-excel#210]
Hi there,

I was wondering if it is possible to export data horizontally, not vertically - let me explain what I mean by that:

Currently, I receive data in the following format:

Questions
First Question
Second Question
Third Question

What I want to get is

Questions        First Question        Second Question        Third Question

Is there any way to do this?

Thanks in advance.

**Comment by BrutusBossNL** [comment]
@mikeladon Hi, I just added this functionality in my pull request. Waiting for the owner to test (and merge) this.
https://github.com/rap2hpoutre/fast-excel/pull/211

**Comment by rap2hpoutre** [comment]
Fixed via https://github.com/rap2hpoutre/fast-excel/pull/211 thanks to @BrutusBossNL available in v2.5.0
