### ISSUE TITLE
Export not working in Laravel 7

### ISSUE THREAD

**Issue by jishadp** [rap2hpoutre/fast-excel#216]
I  upgraded Laravel version 5.8 to 7 and now the export functionality is not working. 

Please tell me which is the compatible version for Laravel Framework version 7.30.4

**Comment by rap2hpoutre** [comment]
I just updated **fast-excel** to be compatible with latest version versions of PHP and Laravel. Could you try to install the `v3.0.0`: `composer require rap2hpoutre/fast-excel:^3`? Let me know if it fixes your issue.
