### ISSUE TITLE
Multi dimension Array

### ISSUE THREAD

**Issue by programmermarvin** [rap2hpoutre/fast-excel#22]
Can not export multi-dimension array

**Comment by rap2hpoutre** [comment]
Thank you for contributing! 

> Can not export multi-dimension array

Yes, non-string values [are removed](https://github.com/rap2hpoutre/fast-excel/blob/master/src/Exportable.php#L116) from the collection. 

Still, exporting a multi-dimension array requires some design. What do you expect? Could you please elaborate?

**Comment by rap2hpoutre** [comment]
@programmermarvin Any news?
