### ISSUE TITLE
Issue when try to call rowsStyle()

### ISSUE THREAD

**Issue by clubedemidia** [rap2hpoutre/fast-excel#230]
Hey guys, I'm trying to customize my file and when I try to add some styles to rows using the rowsStyle method I got the fellow issue _Call to undefined method Box\Spout\Writer\XLSX\Writer::addRowsWithStyle()_

**Comment by AsmaaShAli** [comment]
Hey, can you please check my solution to this issue @rap2hpoutre 
[here](https://github.com/rap2hpoutre/fast-excel/pull/231)

**Comment by rap2hpoutre** [comment]
fixed via https://github.com/rap2hpoutre/fast-excel/pull/231 thanks to @AsmaaShAli
