### ISSUE TITLE
count array = 0

### ISSUE THREAD

**Issue by havantuan** [rap2hpoutre/fast-excel#26]
$first_row = $this->data->first();
foreach ($first_row as $item) {
            if (!is_string($item)) {
                $need_conversion = true;
            }
        }
Check $first_row not null and foreach.

**Comment by rap2hpoutre** [comment]
Thank you for your contribution! Feel free to submit a PR if you want to fix it (or I can do it myself, as you want!)

**Comment by havantuan** [comment]
Excel found unreadable content in file excel. Do you want to recover the contents of the this workbook.
Why I choose yes, then press no I can open file.

**Comment by rap2hpoutre** [comment]
Fixed in v0.3.2. Update your dependencies to this version to make it work with empty things.
