### ISSUE TITLE
Composer says Dependancy "Package box/spout is abandoned"

### ISSUE THREAD

**Issue by tech62** [rap2hpoutre/fast-excel#275]
`Package box/spout is abandoned, you should avoid using it. No replacement was suggested.`

composer why box/spout
rap2hpoutre/fast-excel v3.2.0 requires box/spout (^3)

Any replacement is planned ?

**Comment by henryavila** [comment]
A good alternative could be: https://github.com/openspout/openspout

**Comment by MarkAusten** [comment]
Except that OpenSpout v4 has breaking changes which will require fast-excel to be rewritten. Still, maybe Raphaël will find the time and inclination to do this. Otherwise, the warning will remain.

**Comment by henryavila** [comment]
Hi @MarkAusten and @rap2hpoutre, the openSpout v3 has no break change. It's  fully compatible.
I've created the PR #276 that migrate to OpenSpout v3 and fix the erros on php 8.1. 
All tests are green on local phpunit and on Github Actions

**Comment by henryavila** [comment]
Hi @MarkAusten, The v3 of OpenSpout has no break change.
I created the PR #277 to fix this problem. The unit tests are green and fixed the php 8.1 problem

**Comment by rap2hpoutre** [comment]
Thank you for your feedback! It as been released thanks to @henryavila. Available in v4.0.0
