### ISSUE TITLE
Support PHP 8.2 (update `openspout/openspout`)

### ISSUE THREAD

**Issue by lptn** [rap2hpoutre/fast-excel#301]
This package uses dependency `openspout/openspout` of the old major version v3 that doesn't support PHP 8.2

https://github.com/rap2hpoutre/fast-excel/blob/724557e844170a231fd4515bbc3ea435ca622e7d/composer.json#L15

openspout/openspout supports PHP 8.2 from  https://github.com/openspout/openspout/releases/tag/v4.8.0

Partially duplicate of the https://github.com/rap2hpoutre/fast-excel/issues/288 (#288 is a single solution to solve PHP 8.2 issue)

**Comment by rap2hpoutre** [comment]
Released in 5.0.0
