### ISSUE TITLE
Wrong date formatting

### ISSUE THREAD

**Issue by omegachien** [rap2hpoutre/fast-excel#31]
I have an excel with date column 2018-07-01, but after importing it appears to be a DateTime object 

```
 DateTime @1404086400 {#645 ▼
        date: 2014-06-30 00:00:00.0 UTC (+00:00)
      }
```

The year seems to be off by 4 years, or alternatively is there a way to disable the date formatting? I notice that in `RowInterator.php`'s constructor we can actually pass in `$options`.

**Comment by rap2hpoutre** [comment]
Thank you for your contribution. Could you please provide a (minimal) example of an Excel that produce the bug? I could add it to the unit tests and fix the bug!
