### ISSUE TITLE
null handling

### ISSUE THREAD

**Issue by janokary** [rap2hpoutre/fast-excel#32]
If in the first line of the outputted excel there is a null value then all columns are mixed up in the following lines.

Any suggestions?

**Comment by rap2hpoutre** [comment]
Thank you for your contribution. Could you please provide a (small) example of an Excel that produce the bug? I could add it to the unit tests and fix the bug!

**Comment by janokary** [comment]
When there are nulls values the null cells are skipped (or better missing) end the rest of the line is shifted to the left. 

[file-3.xlsx](https://github.com/rap2hpoutre/fast-excel/files/2169412/file-3.xlsx)

**Comment by rap2hpoutre** [comment]
I can not reproduce the problem. I tried this but it's OK (no bugs):

```php
$original_collection = collect([
    ['col1' => 'val1', 'col2' => 'val2'],
    ['col1' => null, 'col2' => 'val2'] // <= the "null" value is here. 
]);

$filename = __DIR__ . '/test2.xlsx';

(new FastExcel($original_collection))->export($filename);
$res = (new FastExcel())->import($filename);

$this->assertEquals($original_collection, $res); // <= My unit test is green, success

unlink($filename);
```

Could you paste a relevant part of your collection (thank you for your time!)?

**Comment by janokary** [comment]
this is my example (full of nulls):
[code.txt](https://github.com/rap2hpoutre/fast-excel/files/2169853/code.txt)

**Comment by rap2hpoutre** [comment]
Thank you! Fixed via b8f3fecc0b875dd7c474cdbb4ce7ee62839e1f7b, available in v0.4.0 (just update your version with composer and it should work!). Let me know if something went wrong!

**Comment by rap2hpoutre** [comment]
Also, I added a unit test with your case, thanks to you: https://github.com/rap2hpoutre/fast-excel/blob/dd31e838f6e733fe569c193380765394a4c53d5f/tests/IssuesTest.php#L96-L112

**Comment by janokary** [comment]
It is fixed. You are super cool.

**Comment by rap2hpoutre** [comment]
Thank you!

**Comment by mrwcjoughin** [comment]
@rap2hpoutre I am using the latest nuget package and it seems this issue is happening again?
if a cell is blank then the cell is not being included in the cells enumeration for that row at all?
how has this regressed if there is a test for it?

**Comment by cedrictwillie** [comment]
I believe I am experiencing the same issue on version `v5.3.0`..
