### ISSUE TITLE
How to import with matching columns?

### ISSUE THREAD

**Issue by benstaf** [rap2hpoutre/fast-excel#324]
I want to import a CSV file, but I don't want it to fit a pre-established structure, I want to match columns by hand, like in this demo:
https://blog.quickadminpanel.com/how-to-import-csv-in-laravel-and-choose-matching-fields/

is it possible with Fast-excel?

**Comment by vamshikrishnaakula** [comment]
Bro have you done with these ..my case is to upload excel with mapping database fields and above code code where he used the laravel excel package

**Comment by rap2hpoutre** [comment]
Fast Excel aims to resolve simple cases. Maybe for this typical case, you could use https://laravel-excel.com/
