### ISSUE TITLE
The empty cells in excel is considered as string (""), which should be NULL.

### ISSUE THREAD

**Issue by anuragyadav8949** [rap2hpoutre/fast-excel#326]
Response from ExcelExport for sheet with
["column1"]=> int(1) ["column2"]=>NULL

Response from FastExcel on the sheet
["column1"]=>int(1) ["column2"]=>string(0) ""

Did the var dump and found this, while doing importSheets() the empty cells records are coming as empty string and
'column2' => $value['column2'] ?? null, check is failing, which is giving value as "", instead of null
@rap2hpoutre @StyleCIBot

**Comment by StefanoTesla** [comment]
Not true, from the beginning of this library empry cells was returned as "".

**Comment by rap2hpoutre** [comment]
Thank you for your question @anuragyadav8949 and thank you for explanations @StefanoTesla (and sorry for your headache!).

I guess it's OK to keep it like this. By the way, maybe you can map over the collection to fix the null/empty issue?
