### ISSUE TITLE
How to ignore sep=; when importing CSV

### ISSUE THREAD

**Issue by webhoes** [rap2hpoutre/fast-excel#327]
I have files that contain sep=; or sep=, in each file at the top of that file.
As this is seen as a column I can not import the files.

How can I ignore or remove this tag.

I have another of detecting the seperator type, so I don't need it for that function.

**Comment by rap2hpoutre** [comment]
Thank you for your question. Maybe you could edit the file first (with a PHP function) then import it? Let me know if it fixes your issue.
