### ISSUE TITLE
Add SheetCollection class 

### ISSUE THREAD

**Issue by rap2hpoutre** [rap2hpoutre/fast-excel#34]
Create a class `SheetCollection` that extends `Collection` with nothing more for now (so an empty class). It prepares the evolution of export/import system. See https://github.com/rap2hpoutre/fast-excel/pull/24#issuecomment-396255424

**Comment by shoutoutloud** [comment]
Hi. I can be helpful. What should I do?

**Comment by rap2hpoutre** [comment]
Thank you for your proposition! This ticket is a tiny task, but it prepares a greater feature! 

Some more context: currently, we can only import and export **one sheet**. It's OK for simple cases, but it could be better if _optionally_, we could import/export **more sheets**. The original ticket is here: https://github.com/rap2hpoutre/fast-excel/issues/29. After posting this ticket, I had a long (and really interesting) discussion with @Harti in this PR: https://github.com/rap2hpoutre/fast-excel/pull/24, and we created a roadmap, thanks to our discussion, in this comment: https://github.com/rap2hpoutre/fast-excel/pull/24#issuecomment-396255424.

So, I think you have to : 
 - Read briefly the original tickets (mentioned above) to understand the context.
 - Create an empty `SheetCollection` class that extends `Collection` in `src` forder.
 - Send a PR when you created the file.
 - After that, if you want, we could tackle together the next issue: https://github.com/rap2hpoutre/fast-excel/issues/35 (which is a bit more complex).

Feel free to ask me anything!

**Comment by shoutoutloud** [comment]
@rap2hpoutre Thank you for elaborating things.I can create the `SheetCollection` class but I may not be of much help after that as I am just a newbie.

**Comment by rap2hpoutre** [comment]
No problem, it's OK!

**Comment by rap2hpoutre** [comment]
Fixed, available in v0.5.0 thx!
