### ISSUE TITLE
Export / Import Excel in Server "This site can’t be reached"

### ISSUE THREAD

**Issue by Ramonivandy** [rap2hpoutre/fast-excel#42]
I got error when trying to export / import excel from my server

`This site can’t be reached`

Have some solution ?

**Comment by elminson** [comment]
Please add some screenshots.

**Comment by elminson** [comment]
Also add environment(mac, windows, safari etc)

**Comment by Ramonivandy** [comment]
![image](https://user-images.githubusercontent.com/36778458/43440279-ea96a5a8-94c0-11e8-8911-01853dcb858c.png)

on windows.

**Comment by elminson** [comment]
Hi, @Ramonivandy sorry for the delay (working in others projects), I try your example and works. 
this is a work arrow for your case. 
1) if you are using php7 verify if have php7-zip if not please install `php7-zip` and restart (apache or ngnix)

2) if the point 1 dont' work then try force the download type
```php
header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment;filename="your_name.xls"');
header('Cache-Control: max-age=0');
// Do your stuff here
$excel->exportSample();
```

if these not work you will need to debug your environment, probably lock over the /var/log path and see when you try to request the page what happen in the log also turn on the error reporting and look over errors_log file (apache or ngnix) , this will guide you why this error, plese post any update.

**Comment by rap2hpoutre** [comment]
Closed due to lack of activity. Feel free to re-open :).

(PS: thanks to @elminson!)

**Comment by Pelegrinetti** [comment]
Hi, I have the same problem. I tried the @elminson steps but the error still happens.

OS: Ubuntu
PHP: 7.1
Browser: Google Chrome

The error happen when:
```return (new FastExcel($data))->download("file.xlsx");```

P.S.: When *$data* is an array the excel file is generated but is empty, when I convert array to collection this error happen. Browser message: ERR_INVALID_RESPONSE.

**Comment by Thomaasss** [comment]
Hi, same error with php 7.4. My pdf export works on my prod environment (php 7.3.24) but not on my dev environment (php 7.4).
Tried @elminson's solution but that did not solve the problem.

No error in /var/logs/apache2/address-error.log

The access log :
`[24/Sep/2021:13:47:42 +0200] "GET /telecharger-bilan/22 HTTP/1.1" 500 188815 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36"`

**Comment by elminson** [comment]
@Thomaasss the error should be under php no apache 
also the access request is showing that you have an 500 error mean something in your code is not working . 

please share  /var/log/httpd/error_log or /var/log/apache2/error.log

if you dont have those path try this command to get the php error log location 

`php --info | grep error`

**Comment by glowingemp121** [comment]
Hi, same error with php 8.1
