### ISSUE TITLE
How can I export from command line?

### ISSUE THREAD

**Issue by p01ymath** [rap2hpoutre/fast-excel#43]
I want to create an export of models based on my query. There is no fixed query as I export it randomly and based on some parameters. How can I achieve that? I absolutely love your package! just need this feature so that I can export specific users based on my query.

**Comment by rap2hpoutre** [comment]
@p01ymath Is your issue fixed?

**Comment by rap2hpoutre** [comment]
@p01ymath I close this issue, feel free to reopen it if you think your issue is not fixed.
