### ISSUE TITLE
setting title for columns or using  balde 

### ISSUE THREAD

**Issue by Hretic** [rap2hpoutre/fast-excel#48]
hi , is there any option to set the titles for columns ? right now it uses database column names as title alternatively i can use a balde template to set the titles for columns 
is any of these 2 supported ?

**Comment by rap2hpoutre** [comment]
Hi, and thank you for your contribution! 

> i can use a balde template to set the titles for columns

This is not possible :/ You could use [Laravel Excel](https://laravel-excel.maatwebsite.nl/) if you need this kind of options.

> is there any option to set the titles for columns ?

**Yes you can!** You have to use a callback function as a second parameter of the `export` method and specify your column names.

```php
(new FastExcel(User::all()))->export('users.csv', function ($user) {
    return [
        'Email' => $user->email,
        'First Name' => $user->firstname,
        'Last Name' => strtoupper($user->lastname),
    ];
});
```

**Comment by Hretic** [comment]
thanx 

> This is not possible :/ You could use Laravel Excel if you need this kind of options.

i used to work with maatwebsite/excel package but he made it too complicated and hard to work with in the new version , that's why i gave up on that and tried this one 


> Yes you can! You have to use a callback function as a second parameter of the export method and specify your column names.

great , that'll do
