### ISSUE TITLE
Could not open for reading

### ISSUE THREAD

**Issue by Peelz** [rap2hpoutre/fast-excel#53]
This is message **"Could not open /var/www/storage/test.xls for reading! (Could not open /var/www/storage/test.xls for reading.)"**

this is my code .
```php
    public function import(Request $request) {
        // return dd($request->file('import_file')) ;
        $col = (new FastExcel)->import(storage_path('test.xls'));
        return $col; 
    }
```

its just testing code, but not working .
Thanks !

**Comment by rap2hpoutre** [comment]
Hi, thank you for your contribution! Unfortunately, this library only works with xlsx, odt and CSV. So it can't parse XLS files. You could either convert it before or use another lib, such as "laravel Excel"
