### ISSUE TITLE
chinese  GBK make me trouble

### ISSUE THREAD

**Issue by mengdodo** [rap2hpoutre/fast-excel#56]
detail:
b"ÉÌÆ·Ãû³Æ" => b"»ªÎªÈÙÒ«9¸Ö»¯Ä¤v10v9ÈÙÒ«8Çà´º°ænova2sÈ«ÆÁplay¸²¸Ç9iÌùÄ¤mate°Ëp20proÊÖ»úp9p10Ô­×°v8¾Åplus¿¹À¶¹âÈ«°ü±ß"

please help me.....

my code:
$path = storage_path('app/uploads/3.csv');
        (new FastExcel)->import($path, function ($line) {
            dd($line);
        });

**Comment by mengdodo** [comment]
i have solved this problem.

edit FastExcel.php file ,change encoding type

    private $csv_configuration = [
        'delimiter' => ',',
        'enclosure' => '"',
        'eol'       => "\n",
        'encoding'  => 'gbk',
        'bom'       => true,
    ];

**Comment by Pochwar** [comment]
@mengdodo 
Hi, nice if you solve your issue!

By the way, there is a `configureCsv()` method in fast-excel that allows you to do this properly.
Here's an example:
```php
$path = storage_path('app/uploads/3.csv');
(new FastExcel)->configureCsv(',', '"', '\n', 'gbk')->import($path, function ($line) {
    dd($line);
});
```

As `encoding` is the fourth argument of this method, you have to define the tree other before: `delimiter`, `enclosure` and `eol`.

**Comment by rap2hpoutre** [comment]
Thanks @Pochwar !
@mengdodo Did it solve your issue?

**Comment by mengdodo** [comment]
@rap2hpoutre @Pochwar  thanks ,I have solved this problem
