### ISSUE TITLE
Set Maximum row & download multiple file excel

### ISSUE THREAD

**Issue by cybersoftmedia** [rap2hpoutre/fast-excel#58]
Hi, thank you before for this plugin very helping me, i want to ask how to i can set maximum Row & download multiple file, example :
I have 500 row data collection and i want to divide 150, so i have 4 file and download it.
Thank you

**Comment by Pochwar** [comment]
Hi, you can use Laravel Collection's `chunk()` method to achieve this!

From the Laravel Doc:
> The chunk method breaks the collection into multiple, smaller collections of a given size

So you can do something like this:
```php
$users = User::all();
$chunks = $users->chunk(150);

foreach($chunks as $id => $chunk) {
    (new FastExcel($users))->export("file-$id.xlsx");
}
```

Or if you want to export in a single file with sheets, you can do something like that:
```php
$users = User::all();
$chunks = $users->chunk(150);
$sheets = new SheetCollection($chunks);
(new FastExcel($sheets))->export("file-with-sheets.xlsx");
```

**Comment by rap2hpoutre** [comment]
Thanks @Pochwar! 👏 👏  

@cybersoftmedia Did it solve your problem?

**Comment by cybersoftmedia** [comment]
Thank you Mr @Pochwar 
This function just return link ?
how about return download multiple ?
like this :
```
foreach($chunks as $id => $chunk) {
    return (new FastExcel($users))->download("file-$id.xlsx");
}
```
it possible ? i try error.

**Comment by cybersoftmedia** [comment]
Not yet @rap2hpoutre, i need more help.

**Comment by cybersoftmedia** [comment]
@rap2hpoutre thank you, i will try
