### ISSUE TITLE
Using chunk in collection and export to Excel

### ISSUE THREAD

**Issue by Elshaden** [rap2hpoutre/fast-excel#65]
Hi
Thanks for this package, it is extremely fast,

I have problems with memory exhausted  in exporting over 300K, rows.

I need to chunk the exported data, to save memory,
how can this be done.?

**Comment by rap2hpoutre** [comment]
Thank you!

Not sure it will answer your question, but you can chunk data and export multiple excels files:
```php
$users = User::all();
$chunks = $users->chunk(1000);

foreach($chunks as $id => $chunk) {
    (new FastExcel($users))->export("file-$id.xlsx");
}
```

(it will create `N` files).

**Comment by markdieselcore** [comment]
I think he's asking if there's a way to chunk data while exporting one excel file?

**Comment by Elshaden** [comment]
Hi, Thanks for the reply,
as maekdieselcore said, I want to export a one sheet excel from chunks of data, in a foreach chunk  add to excel loop.
this way I can export large number of rows. without exhausting  memory.

**Comment by Elshaden** [comment]
if all fails I will have to split the chunks into different files. I like the speed of your package, I guess I have to compromise something.

**Comment by markdieselcore** [comment]
@rap2hpoutre I think maybe it's time to revisit chunking for the package? People will use this package because it's fast, and their needs will gravitate towards bigger data sets.

**Comment by rap2hpoutre** [comment]
@markdieselcore Yes you are right! Not sure about the implementation though. Maybe we could follow the same pattern as for `SheetCollection`, something like `ChunkCollection` (then the export method would process chunks by chunks)...

**Comment by mtownsend5512** [comment]
@rap2hpoutre I'm not opposed to working on this myself. I just haven't read through the Spout library yet. I'll begin reviewing it soon to better understand how it works. Just trying to think through how the syntax would read.

**Comment by mengdodo** [comment]
@rap2hpoutre  hello, export big data into one excel file by chunk , is that ok ?  i need this method

**Comment by rap2hpoutre** [comment]
@mengdodo this is not developed yet, but it seems important, so I will try to do something about that!

**Comment by elminson** [comment]
I can contribute! Just hit me up!

**Comment by rap2hpoutre** [comment]
I just created a **draft** PR for this issue: https://github.com/rap2hpoutre/fast-excel/pull/112/files

The idea is to use [generators](https://www.php.net/manual/en/language.generators.syntax.php), which seems to have been build for this exact kind of need. With my (quick) tests, for about 100k lines, it only use ~5M of RAM versus ~50M without chunks. 🎉 

To make it work, you have to create a _generator_ function using `yield` then pass it to `FastExcel`:

```php
// Generator function
function getUsersOneByOne() {
    // build your chunks as you want (200 chunks of 10 in this example)
    for ($i = 0; $i < 200; $i++) {
        $users = DB::table('users')->skip($i * 10)->take(10)->get();
        // Yield user one by one
        foreach($users as $user) {
            yield $user;
        }
    }
}

// Export consumes only a few MB
(new FastExcel(getUsersOneByOne()))->export('test.xlsx');
```

Minimal (shorter) example:

```php
function myGenerator() {
    $users = get_users_as_you_want();
    foreach($users as $user) {
        yield $user;
    }
}

(new FastExcel(myGenerator()))->export('test.xlsx');
```


What do you think about this implementation @mengdodo @ArturoGasca @Elshaden @markdieselcore ? Could it solve your problem?

**Comment by rap2hpoutre** [comment]
Another (more readable, with "real" chunks) example:

```php
function usersGenerator() {
    yield from User::chunk(200, function($users) {
        foreach($users as $user) {
            yield $user;
        }
    });
}

// Export consumes only a few MB
(new FastExcel(usersGenerator()))->export('test.xlsx');
```

**Comment by rap2hpoutre** [comment]
Fixed, available in v1.3.0 :tada:

**Comment by rap2hpoutre** [comment]
Article here: https://dev.to/rap2hpoutre/export-10m-rows-in-xlsx-with-laravel-without-memory-issues-6bk

**Comment by ehsanhoushmand** [comment]
Showing Error: Can use "yield from" only with arrays and Traversables. Can you help?

**Comment by alexbabich1990** [comment]
I have the same problem

**Comment by qlixes** [comment]
@ehsanhoushmand @alexbabich1990 please go to https://dev.to/rahulprgrmr/comment/f1lk

**Comment by joshbaumann** [comment]
For what is it worth, the following also solves the `yield from` issue with using the `chunks` method.

Using the `lazy` method did the trick for me.

```
function resultsGenerator(Builder $query) {
    yield from $query->lazy();
}
```
