### ISSUE TITLE
FastExcel with Storage

### ISSUE THREAD

**Issue by g-trema** [rap2hpoutre/fast-excel#69]
Hi!
Thank you for this great library!
I try to import an excel file in the Storage folder.

```
$file = Storage::disk('public')->url('Keywords.xlsx')
$collection = (new FastExcel)->import($file);
```

But I have this error:

> `Could not open http://projectname.oo/documentations/Keywords.xlsx for reading! Stream wrapper used is not supported for this type of file.`

And with the same file placed in the public folder, there is no problem...
Is that problem is knew? or what am I doing wrong?

Thank you!

**Comment by rap2hpoutre** [comment]
@g-trema Hi and thank you for your contribution! 

The `url` method refers to an URL, not a local filesystem. You could replace this:

```
$file = Storage::disk('public')->url('Keywords.xlsx');
```

By:

```
$file = public_path('Keywords.xlsx');
// ... or ...
$file = storage_path('app/public/Keywords.xlsx')
```

**Comment by g-trema** [comment]
Oh yeah... of course!
Thank you very much!!!

**Comment by JakeOcean** [comment]
Is it possible to use this with files hosted on a remote file system using the Storage facade?

I am uploading files to S3 and getting the same error above.  I am unable to move the files to the local filestem

**Comment by bernard-murunga** [comment]
@JakeOcean were you able to store the export in S3?

**Comment by PORRIS** [comment]
Someone was able to import from a remote repository like s3?

**Comment by aleedksa** [comment]
No not yet, I think for that we have to go to our old `maatwebsite/excel`.
