### ISSUE TITLE
errore when read a datetime

### ISSUE THREAD

**Issue by maxdiable** [rap2hpoutre/fast-excel#70]
i want load a xls, but when read a datetime, laravel show this error:
Undefined property: DateTime->$date

any help ?
br Max

**Comment by rap2hpoutre** [comment]
Hi and thank you for your contribution! Could you post your code and the
whole error stack trace?

**Comment by maxdiable** [comment]
Hi,
I resolved
BR
Max

Il ven 26 ott 2018, 18:11 Raphaël Huchet <notifications@github.com> ha
scritto:

> Hi and thank you for your contribution! Could you post your code and the
> whole error stack trace?
>

**Comment by klukiyan** [comment]
@maxdiable @rap2hpoutre 
how did you fix it?
How to make dates appear as one sigle date field instead of object with 3 elements?

**Comment by maxdiable** [comment]
Yes,
Today i have resolved
BR
Max

Il giorno lun 5 nov 2018, 17:55 Kiril Lukiyan <notifications@github.com> ha
scritto:

**Comment by klukiyan** [comment]
@maxdiable how did you resolve it. I have the same issue. I need date fields to be dates, not objects

**Comment by maxdiable** [comment]
Hi,
Tomorrow i send you my solution,
Now i not are in Office
BR
Max

Il giorno lun 5 nov 2018, 18:33 Kiril Lukiyan <notifications@github.com> ha
scritto:

**Comment by klukiyan** [comment]
thank you. I'll wait

**Comment by maxdiable** [comment]
hi,
this is my code:

private static function importRighe($request, $id_testata) {
        try {
            $num_trans = "";
            $data = "";
            $item = null;

            if ($request->hasfile('upload')) {
                foreach ($request->file('upload') as $file) {
                    $contents = $file->openFile()->fread($file->getSize());
                    $filename = $file->getClientOriginalName();

                    $path = $_SERVER['DOCUMENT_ROOT'] . "/" .
config("app.folder_upload") . "/" . $filename;
                    $ext = strtolower(pathinfo($path, PATHINFO_EXTENSION));

                    $fp = fopen($path, "w");
                    fwrite($fp, $contents);
                    fclose($fp);

                    if ($ext === "csv") {
                        $data = (new
FastExcel)->configureCsv(';')->import($path);
                    } else {
                        $data = (new FastExcel)->import($path);
                    }

                    foreach ($data as $key => $value) {
                        $obj = new Tbc_FlussoSapRiga;
                        $obj->id_testata = $id_testata;
                        $items = array_values($value);
                        $num_trans = "Num. doc. contabile: " . $items[1] .
" - pos: " . $items[2];
                        $obj->anno_doc =
Uty::ConvertToNumberOracle($items[0]);
                        $obj->num_doc_cont = $items[1];
                        $obj->pos_doc_cont =
Uty::ConvertToNumberOracle($items[2]);
                        $obj->tipo_ord_acq = $items[3];
                        $obj->num_doc_acq = $items[4];
                        $obj->pos_doc_acq =
Uty::ConvertToNumberOracle($items[5]);
                        if ($ext === "csv") {
                            $obj->data_doc =
Carbon::createFromFormat('d/m/Y', $items[6], 'Europe/Rome');
                            $obj->data_reg =
Carbon::createFromFormat('d/m/Y', $items[7], 'Europe/Rome');
                            $obj->data_acq =
Carbon::createFromFormat('d/m/Y', $items[8], 'Europe/Rome');
                        } else {
                            $obj->data_doc = $items[6]->format('Y-m-d');
                            $obj->data_reg = $items[7]->format('Y-m-d');
                            $obj->data_acq = $items[8]->format('Y-m-d');
                        }
                        $obj->riferimento = $items[9];
                        $obj->testo_doc = $items[10];
                        $obj->testo_breve = $items[11];
                        $obj->wbs = $items[12];
                        $obj->id_fornitore_sap =
Uty::ConvertToNumberOracle($items[13]);
                        $obj->d_fornitore = $items[14];
                        $obj->coge = $items[15];
                        $obj->testo_esteso = $items[16];
                        $obj->tipo_mov = $items[17];
                        $obj->importo =
Uty::ConvertToDecimalOracle($items[18], 2, ",", "");
                        if (trim($obj->tipo_mov) !== "101") {
                            $obj->importo = "-" . $obj->importo;
                        }
                        $obj->divisa = $items[19];

                        $obj->save();
                    }
                }
            }
        } catch (\Exception $ex) {
            Log::error("Num. Trans:" . $num_trans . " - " .
$ex->getMessage());
            throw new \Exception($ex->getMessage());
        }
    }
br
Max

Il giorno lun 5 nov 2018 alle ore 19:05 Kiril Lukiyan <
notifications@github.com> ha scritto:

> thank you. I'll wait
>
