### ISSUE TITLE
Can't import an excel with dateTime cell

### ISSUE THREAD

**Issue by aalyusuf** [rap2hpoutre/fast-excel#72]
Hey,

When I try to import an excel with datetime cell , I get the following error:

```Object of class DateTime could not be converted to string```

This would be solved using ```$reader->setShouldFormatDates(true);``` but there's no way to access reader directly.

Example file that produces this issue: [DateTest.xlsx](https://github.com/rap2hpoutre/fast-excel/files/2545849/DateTest.xlsx)

**Comment by rap2hpoutre** [comment]
Thank you for your contribution and sorry for the delay. It's fixed via https://github.com/rap2hpoutre/fast-excel/commit/b92c19b0a217ad17f140b706c34f2ca76107e926 and available in v0.12.0
