### ISSUE TITLE
How can I get sheet name?

### ISSUE THREAD

**Issue by TeslaX93** [rap2hpoutre/fast-excel#74]
Is it possible in fastExcel?

**Comment by rap2hpoutre** [comment]
Hello, thank you for your contribution! There is currently no way to get the sheet name.

Still, you can get a sheet by its number:

```
$users = (new FastExcel)->sheet(3)->import('file.xlsx');
```

**Comment by sough** [comment]
Hello, thx for this lib, but how to import only last sheet?

**Comment by markdieselcore** [comment]
```php
$sheets = new SheetCollection([
    'Users' => User::all(),
    'Second sheet' => Project::all()
]);

$projects = (new FastExcel)->sheet($sheets->last())->import('file.xlsx');
```

**Comment by sough** [comment]
Thx, but I don't have $sheets before import. Its random excel file

**Comment by rap2hpoutre** [comment]
@sough Here is a (not optimized) workaround for your problem:

```php
$last_sheet = (new FastExcel)->importSheets('file.xlsx')->last();
```

**Comment by TeslaX93** [comment]
At the moment, I solved my problem with a little help of Box/Spout.

`	
use Rap2hpoutre\FastExcel\FastExcel;
use Box\Spout\Reader\ReaderFactory;
use Box\Spout\Common\Type;

// code...

	        $sheetNames = [];
		$reader = ReaderFactory::create(Type::XLSX);
		$reader->open($file);
		foreach($reader->getSheetIterator() as $sheet)  {
			array_push($sheetNames,$sheet->getName());
		}
		$sheets = (new FastExcel)->importSheets($file);
		
// etc...    
`
