### ISSUE TITLE
How can i print the excel file in fast-excel(solved)

### ISSUE THREAD

**Issue by 879879123** [rap2hpoutre/fast-excel#77]
![image](https://user-images.githubusercontent.com/45756810/49726452-04807480-fca9-11e8-9440-094aacd69c2c.png)

help!! how can i print the object data throught laravel fast-excel
here's  my angular typescript
![image](https://user-images.githubusercontent.com/45756810/49726510-2da10500-fca9-11e8-8184-15c8b39b9676.png)

![image](https://user-images.githubusercontent.com/45756810/49726576-4e695a80-fca9-11e8-8644-77c8285b2cec.png)

**Comment by 879879123** [comment]
i have passed the all request data to 'test' array,but i generate the excel,it's not match for my demand
![image](https://user-images.githubusercontent.com/45756810/49773317-8e712180-fd2b-11e8-8397-1fd2d32ef9d4.png)

![image](https://user-images.githubusercontent.com/45756810/49773329-9b8e1080-fd2b-11e8-9f7e-d7c5462775ca.png)

**Comment by rap2hpoutre** [comment]
Hello, and thank you for your contribution! Since you changed the title to "solved", does this mean you have fixed your problem? Can I close this issue?
