### ISSUE TITLE
how to change cache directory? setTempFolder

### ISSUE THREAD

**Issue by dextherry** [rap2hpoutre/fast-excel#83]
Hi sr, please help me with this
how can I change the location of the cache directory?
in spot docs says the method setTempFolder
how can I set that in fast-excel?

my currenbt fast-excel code is this:

`$style = (new StyleBuilder())
     ->setFontBold()
     ->build();

     return (new FastExcel($list))->headerStyle($style)->download('file.xlsx');`

thanks for your work

**Comment by rap2hpoutre** [comment]
Hi and thank you for your contribution. 

Currently, there is no way to access the `writer` of Spout via FastExcel. Still, I understand your need and maybe we should add an access to spout writer (and then you could set the temporary folder). I will come back to you when it will be implemented.

**Comment by rap2hpoutre** [comment]
@dextherry @ekandreas @delmicio Fixed, thanks to @johanrosenson available in v1.4.0!
