### ISSUE TITLE
data format is worng

### ISSUE THREAD

**Issue by TaejongJang** [rap2hpoutre/fast-excel#84]
first, thank you for your source.

but i have a problem. when i import xlsx data to db, data value converted that "1" to "1900-01-01 00:00:00".
- excel file
![image](https://user-images.githubusercontent.com/21344480/50864411-ce411e00-1356-11e9-9db6-38d513b0f784.png)
- imported DB
![image](https://user-images.githubusercontent.com/21344480/50864469-ffb9e980-1356-11e9-8790-000295eb28a3.png)

i can't understand this situation.

 i'm using fastexcel -v 0.12
![image](https://user-images.githubusercontent.com/21344480/50864257-4824d780-1356-11e9-80c0-e74ad41bf9e7.png)

**Comment by rap2hpoutre** [comment]
Hello, thank you for your contribution! Could you please provide a XLSX sample with your problem, so I could try to reproduce then resolve the issue?
