### ISSUE TITLE
How can i render image while exporting?

### ISSUE THREAD

**Issue by ahmadalshugairi8** [rap2hpoutre/fast-excel#87]

**Comment by rap2hpoutre** [comment]
Could you please explain a bit more what you are trying to achieve? Do you have a problem with "fast-excel" lib?

**Comment by bashiryousufy** [comment]
Hi @rap2hpoutre ,

I have the same request as @alshugairi . I want to insert an image to excel when downloading it. 

I think Laravel-Excel has that feature. I'm not sure if I can achieve it using this package.

https://stackoverflow.com/questions/72758684/export-laravel-excel-image-failed

**Comment by bashiryousufy** [comment]
> Hi @rap2hpoutre ,
> 
> I have the same request as @alshugairi . I want to insert an image to excel when downloading it.
> 
> I think Laravel-Excel has that feature. I'm not sure if I can achieve it using this package.
> 
> https://stackoverflow.com/questions/72758684/export-laravel-excel-image-failed

The Image could be QrCode or Signature.
