### ISSUE TITLE
Export custom data

### ISSUE THREAD

**Issue by mudasserzahid** [rap2hpoutre/fast-excel#88]
Hi, that is an awesome package to implement with laravel. I have done import functionality but I am stuck on export functionality. Here is what I am doing.
`return (new FastExcel(collect($response)))->download('file.xlsx', function($record) {`
`                return $record['data'];`
`            });`
Specified code is returning me a html file download **288e360c-5b96-18f7-eb7e-4fbdfcc4c13a-response.html** , which is containing 
`PKÖ˜SNfï¿½ï¿½vHA[Content_Types].xmlï¿½ï¿½ï¿½Nï¿½0Eï¿½ï¿½ï¿½ï¿½[ï¿½eï¿½Jï¿½ï¿½%Tï¿½|ï¿½ï¿½'ï¿½Uï¿½ï¿½qKï¿½ï¿½Lï¿½UUï¿½@ï¿½lï¿½ï¿½ï¿½=ï¿½\Í¶ï¿½Hhï¿½ï¿½Ù„ï¿½Y^mï¿½ï¿½foï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½5ï¿½ï¿½ï¿½tT-vï¿½ï¿½dï¿½5ksï¿½wBï¿½jï¿½Iï¿½!ï¿½'ï¿½ ï¿½ï¿½LÛ´Qï¿½ï¿½\ï¿½ï¿½ï¿½oï¿½ >ï¿½ï¿½eï¿½jï¿½é¨ ï¿½zï¿½Fï¿½m.ï¿½ï¿½ï¿½_3ï¿½5Jfï¿½Tï¿½ï¿½[ï¿½n/~ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½#ï¿½ï¿½ï¿½ï¿½ï¿½Dï¿½:u!ï¿½l^ï¿½Qï¿½hï¿½ï¿½Ohï¿½@ï¿½vï¿½ï¿½1&ï`
can you please help me in resolving specified issue. Also I want to mention that on export action like;
`return (new FastExcel(collect($response)))->export('file.xlsx', function($record) {`
`                return $record['data'];`
`            });`
It is sending me a proper file which I want. and For more elaboration `$record['data']` is an array in my code

**Comment by rap2hpoutre** [comment]
Hi, thank you for your contribution. 

- What is the whole function that contains this code?
-  Is this in a controller method and is this called via a browser?
 - Could you share the whole file?
 - Does it work _without_ the callback?

**Comment by mudasserzahid** [comment]
Thanks for your reply, here is the answers to your all questions,

**This is environment I am using**

- Lumen 5.6

- PHP 7.2

**This is the code which I am trying**
```
<?php
namespace App/Submission/Request;

use App\Core\Base\Request;
use Model\SubmissionModel;
use Rap2hpoutre\FastExcel\FastExcel;

class ExportRequest extends Request
{
    public function process()
    {
        $response = (new SubmissionModel())->get()->toArray();
         return (new FastExcel(collect($response)))->download('file.xlsx');
    }
}
```

**Answers of your questions***

- I have shared code above which I am tryig in my code.

- This is a controller call but this is API based. XHR can explain it properly. Because Lumen is used to write web services.

- I have already shared above

- Yes it work without callback function, as mention in source code. But output is same as given above.

> For the time being I am exploring your library, there may be one problem that headers are not working fine as it should when request is called from browser. There may changes required when returning value it should update the headers.

**Comment by mudasserzahid** [comment]
Here is the solution of specified exception, the thing about which I am saying was a bad response actually is an accurate response. All the thing you need is work with `Blob` on front and export file to your desired extension. For the time being, I am using Angular JS as a front-end application. I will share also source code for Angular JS if that would be relevant to this repository.
