### ISSUE TITLE
导出无法自定义目录

### ISSUE THREAD

**Issue by mr-1024** [rap2hpoutre/fast-excel#89]
(new FastExcel($data))->export(storage_path('app/downloads/'.'_'.time().'.xlsx'));
实际效果：
G:\website\api\storage\app/downloads_1551167605.xlsx

**Comment by rap2hpoutre** [comment]
Hi, thank you for your contribution! I don't speak chinese and I don't trust google trad for programming issues. Could you please write your question in english? (or ask someone to do it for you?)

**Comment by newbie2005** [comment]
The title is the export function can't export to a user-define directory, but the question is not clear
 -- A Chinese

**Comment by rap2hpoutre** [comment]
@newbie2005 Thank you!!

@mr-1024 Could you please clarify your question?

**Comment by justinmoh** [comment]
_(Translate)_ @rap2hpoutre 

When executing:
```php
(new FastExcel($data))->export(storage_path('app/downloads/'.'_'.time().'.xlsx'));
```

It then produced the result:
```bash
G:\website\api\storage\app/downloads_1551167605.xlsx
```

The issue is that his `storage_path(...)` returning windows path and then he's concatenating it with linux path. It could be just that his laravel setup isn't work properly, I'm not sure.

**Comment by mengdodo** [comment]
I think it's his configure problem.  
not fast-excel project error, haha
suggest closed
