### ISSUE TITLE
Upgrade to Laravel 5.8

### ISSUE THREAD

**Issue by tanaychatterji** [rap2hpoutre/fast-excel#90]
Please make this package compatible with Laravel 5.8
Thanks in Advance....

**Comment by rap2hpoutre** [comment]
Hello, thank you for your contribution! I just updated it (https://github.com/rap2hpoutre/fast-excel/commit/21578f43ed89340dde69bf2ed9ad2bda4ca2dfa8) thanks to your issue, please upgrade this package to v1.2.0.

Have a nice day!

**Comment by tanaychatterji** [comment]
Thank you so much !!
