### ISSUE TITLE
Problems with headers and empty collection

### ISSUE THREAD

**Issue by GabrielPrCs** [rap2hpoutre/fast-excel#92]
Hi! I had a problem while I was trying to create a file that may be empty. If the collection from where the file will be created is empty, I get a problem related with the headers. The error is as follows:

> Call to a member function toArray() on null at  rap2hpoutre/fast-excel/src/Exportable.php#113

And reading the code I saw it trying to get the headings from the first collection item, which does not exists.
```
if ($this->with_header) {
   $first_row = $collection->first();
   $keys = array_keys(is_array($first_row) ? $first_row : $first_row->toArray());
   if ($this->header_style) {
      $writer->addRowWithStyle($keys, $this->header_style);
   } else {
...
```
There is a way to avoid the headings if the collection is empty? Or I need to always give a collection with at least a fake item from where the headings can be taken.

Thank you.

**Comment by rap2hpoutre** [comment]
Hi, thank you for your contribution! Since returning an empty Excel file when collection is empty does not make sense IMO, maybe you could check your collection before exporting. The lib could not find the headings if collection is empty, so there won't be any line.

**Comment by GabrielPrCs** [comment]
I assume the same goes for the SheetCollection, right? Thank you for answering, I think I will try with a previous validation of the filters applied.
