### ISSUE TITLE
hi, when i download file, it has no name

### ISSUE THREAD

**Issue by Bantes** [rap2hpoutre/fast-excel#93]
`$datas = Data::where('group_id', $group->id)->get();

        return (new FastExcel($datas))->download($group->title.'.xlsx', function ($user) {
            return [
                'ID' => $user->id,
                'Name' => $user->name,
                'Mobile' => $user->mobile,
                'Address' => $user->address,
                'Company' => $user->company,
                'Created Time' => $user->created_at,
            ];
        });`

like these codes, i access the method and got a no name file, for example 'xlsx', just a extension name

so what problems did I encounter in my project?

thanks

**Comment by Bantes** [comment]
oh, when i add a string word before the $group->title, like `'test-'.$group->title.'.xlsx', it can download a file with name

**Comment by Bantes** [comment]
it's not friendly to chinese file names, and i find it's must start with english name

**Comment by rap2hpoutre** [comment]
Hello, thank you for your contribution.

I just tried and it seems to work with chinese filenames. I created a unit test for this and it works: https://github.com/rap2hpoutre/fast-excel/blob/master/tests/IssuesTest.php#L145

https://github.com/rap2hpoutre/fast-excel/blob/b11f66d5d7833262c4a02a0c63cc6d3d560ae0a3/tests/IssuesTest.php#L143-L147

You could check in the continuous integration tool here: https://travis-ci.org/rap2hpoutre/fast-excel/jobs/506654192#L562

I think there must be another error on your code, or maybe it's something about your Operating System, but it seems it's not a problem with the lib itself.

**Comment by phithakul** [comment]
https://laravel.com/docs/5.8/responses#file-downloads
as document says: Symfony HttpFoundation, which manages file downloads, requires the file being downloaded to have an ASCII file name.
