### ISSUE TITLE
How can I fit column width to data

### ISSUE THREAD

**Issue by mustafaelagamey** [rap2hpoutre/fast-excel#96]
When Exporting data to the file the column width is to small for data
how can i make column width fit data

**Comment by rap2hpoutre** [comment]
Hi, thank you for your contribution! It's actually not possible.  This package is based on Spout which can not handle this need. See: https://github.com/box/spout/issues/129

**Comment by rap2hpoutre** [comment]
Be sure I will implement it when it's ready in Spout.

**Comment by humbertleonardo** [comment]
Any predictions for release of this update? I saw that the openspout package already implemented the setColumnWidth() function. Is there a possibility of using it?

**Comment by humbertleonardo** [comment]
I was able to set the column width manually using the "configureWriterUsing" function like this below

![image](https://user-images.githubusercontent.com/57204453/209600311-3f2839ba-cc7d-408d-bdc7-af12d833ede7.png)

**Comment by tajweb** [comment]
Any updates?

**Comment by a-zog** [comment]
`configureWriterUsing()
` seems to be deprecated and doesn't seem to work, any alternatives please?

**Comment by Martin-Matchory** [comment]
`(new FastExcel($list))->configureOptionsUsing(function ($writer) {

                // see what's possible:  var_export($writer);
                $writer->DEFAULT_COLUMN_WIDTH = 40;
                $writer->DEFAULT_ROW_HEIGHT = 20;
    
            })
              ...
                ->export....`

**Comment by datfunnydev** [comment]
> `(new FastExcel($list))->configureOptionsUsing(function ($writer) { $writer->DEFAULT_COLUMN_WIDTH = 40; $writer->DEFAULT_ROW_HEIGHT = 20; })`

How about setting the width for each column?

**Comment by devfake** [comment]
> > `(new FastExcel($list))->configureOptionsUsing(function ($writer) { $writer->DEFAULT_COLUMN_WIDTH = 40; $writer->DEFAULT_ROW_HEIGHT = 20; })`
> 
> How about setting the width for each column?

@datfunnydev 

You can use the `setColumnWidthForRange` method for that:

```
        ->configureOptionsUsing(function (\OpenSpout\Writer\Common\AbstractOptions $options) {
            $options->setColumnWidthForRange(30, 1, 1);
        })
```
