### ISSUE TITLE
how can i custom excel content

### ISSUE THREAD

**Issue by mengdodo** [rap2hpoutre/fast-excel#97]
as i kown, i can export excel/csv by laravel Collection
```
(new FastExcel($invoices))->export('invoices.csv');
```
but how can i diy custom content
for example:

the yellow area, how can i do it @elminson ?

![image](https://user-images.githubusercontent.com/21698573/56340979-2c975b80-61e6-11e9-9c3d-f2b362007461.png)

**Comment by rap2hpoutre** [comment]
Hi, thank you for your contribution! It's actually not possible. Still, you can add some basic style on header: https://github.com/rap2hpoutre/fast-excel/issues/4#issuecomment-433315395

```php
use Box\Spout\Writer\Style\StyleBuilder;

$style = (new StyleBuilder())
    ->setFontBold()
    ->setBackgroundColor(Color::YELLOW)
    ->build();

(new FastExcel(User::all()))
    ->headerStyle($style)
    ->export('my-file.xlsx');
```
