### ISSUE TITLE
Handle a +70k rows csv import ?

### ISSUE THREAD

**Issue by tony5Dim** [rap2hpoutre/fast-excel#98]
I have 5 CSV files (up to 70k rows) to import. The process (of one file import only) can exhaust the PHP memory or time_limit.

How can I chunk the imports to process the data each 500/1000 rows without stocking the whole import in an array ,so I can save some ressource ?

**Comment by rap2hpoutre** [comment]
Hi, thank you for your contribution! You could have a look here: https://github.com/rap2hpoutre/fast-excel/issues/82#issuecomment-453391983.

There is also a proposal here: https://github.com/rap2hpoutre/fast-excel/issues/65

**Comment by tony5Dim** [comment]
Finaly I did 
`$handle = fopen($fileName, "r");
if($handle){
            while (($buffer = fgets($handle)) !== false) {
                      $explode = explode("|", utf8_encode($buffer));
                      etc...
            }
fclose($handle);`

That is a fine way to save the memory
