### ISSUE TITLE
fastexcel($list)->download(...)  is not support to laravel-swoole  

### ISSUE THREAD

**Issue by zhongjq** [rap2hpoutre/fast-excel#99]
fastexcel($list)->download(...)  is not support to laravel-swoole  
 [FYI](https://github.com/swooletw/laravel-swoole/wiki/Z1.-Notices)

![image](https://user-images.githubusercontent.com/1228323/57203900-4d352300-6fe6-11e9-877c-ecf737e42f14.png)

**Comment by rap2hpoutre** [comment]
Hi and thank you for your contribution!

Could you try to use the `export` method then use the standard laravel method for downloading? (https://laravel.com/docs/5.6/responses#file-downloads)

Example:

```php
public function myActionInAController() {
    (new FastExcel(User::all()))->export('file.xlsx'); // <- replace "download" by "export"
    return response()->download('file.xlsx'); // <- use the builin version from Laravel
}
```

**Comment by zhongjq** [comment]
Yes, I was do that now. Thank you
